"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MeasurementUpdateToJSON = exports.MeasurementUpdateFromJSONTyped = exports.MeasurementUpdateFromJSON = void 0;
var runtime_1 = require("../runtime");
function MeasurementUpdateFromJSON(json) {
    return MeasurementUpdateFromJSONTyped(json, false);
}
exports.MeasurementUpdateFromJSON = MeasurementUpdateFromJSON;
function MeasurementUpdateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'note': !(0, runtime_1.exists)(json, 'note') ? undefined : json['note'],
        'startTime': !(0, runtime_1.exists)(json, 'startTime') ? undefined : json['startTime'],
        'value': !(0, runtime_1.exists)(json, 'value') ? undefined : json['value'],
    };
}
exports.MeasurementUpdateFromJSONTyped = MeasurementUpdateFromJSONTyped;
function MeasurementUpdateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'note': value.note,
        'startTime': value.startTime,
        'value': value.value,
    };
}
exports.MeasurementUpdateToJSON = MeasurementUpdateToJSON;
//# sourceMappingURL=MeasurementUpdate.js.map