"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MeasurementToJSON = exports.MeasurementFromJSONTyped = exports.MeasurementFromJSON = exports.MeasurementVariableCategoryNameEnum = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
/**
* @export
* @enum {string}
*/
var MeasurementVariableCategoryNameEnum;
(function (MeasurementVariableCategoryNameEnum) {
    MeasurementVariableCategoryNameEnum["Activity"] = "Activity";
    MeasurementVariableCategoryNameEnum["Books"] = "Books";
    MeasurementVariableCategoryNameEnum["CausesOfIllness"] = "Causes of Illness";
    MeasurementVariableCategoryNameEnum["CognitivePerformance"] = "Cognitive Performance";
    MeasurementVariableCategoryNameEnum["Conditions"] = "Conditions";
    MeasurementVariableCategoryNameEnum["Emotions"] = "Emotions";
    MeasurementVariableCategoryNameEnum["Environment"] = "Environment";
    MeasurementVariableCategoryNameEnum["Foods"] = "Foods";
    MeasurementVariableCategoryNameEnum["Goals"] = "Goals";
    MeasurementVariableCategoryNameEnum["Locations"] = "Locations";
    MeasurementVariableCategoryNameEnum["Miscellaneous"] = "Miscellaneous";
    MeasurementVariableCategoryNameEnum["MoviesAndTv"] = "Movies and TV";
    MeasurementVariableCategoryNameEnum["Music"] = "Music";
    MeasurementVariableCategoryNameEnum["Nutrients"] = "Nutrients";
    MeasurementVariableCategoryNameEnum["Payments"] = "Payments";
    MeasurementVariableCategoryNameEnum["PhysicalActivities"] = "Physical Activities";
    MeasurementVariableCategoryNameEnum["Physique"] = "Physique";
    MeasurementVariableCategoryNameEnum["Sleep"] = "Sleep";
    MeasurementVariableCategoryNameEnum["SocialInteractions"] = "Social Interactions";
    MeasurementVariableCategoryNameEnum["Software"] = "Software";
    MeasurementVariableCategoryNameEnum["Symptoms"] = "Symptoms";
    MeasurementVariableCategoryNameEnum["Treatments"] = "Treatments";
    MeasurementVariableCategoryNameEnum["VitalSigns"] = "Vital Signs";
})(MeasurementVariableCategoryNameEnum = exports.MeasurementVariableCategoryNameEnum || (exports.MeasurementVariableCategoryNameEnum = {}));
function MeasurementFromJSON(json) {
    return MeasurementFromJSONTyped(json, false);
}
exports.MeasurementFromJSON = MeasurementFromJSON;
function MeasurementFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'card': !(0, runtime_1.exists)(json, 'card') ? undefined : (0, _1.CardFromJSON)(json['card']),
        'clientId': !(0, runtime_1.exists)(json, 'clientId') ? undefined : json['clientId'],
        'connectorId': !(0, runtime_1.exists)(json, 'connectorId') ? undefined : json['connectorId'],
        'createdAt': !(0, runtime_1.exists)(json, 'createdAt') ? undefined : json['createdAt'],
        'displayValueAndUnitString': !(0, runtime_1.exists)(json, 'displayValueAndUnitString') ? undefined : json['displayValueAndUnitString'],
        'iconIcon': !(0, runtime_1.exists)(json, 'iconIcon') ? undefined : json['iconIcon'],
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'inputType': !(0, runtime_1.exists)(json, 'inputType') ? undefined : json['inputType'],
        'ionIcon': !(0, runtime_1.exists)(json, 'ionIcon') ? undefined : json['ionIcon'],
        'manualTracking': !(0, runtime_1.exists)(json, 'manualTracking') ? undefined : json['manualTracking'],
        'maximumAllowedValue': !(0, runtime_1.exists)(json, 'maximumAllowedValue') ? undefined : json['maximumAllowedValue'],
        'minimumAllowedValue': !(0, runtime_1.exists)(json, 'minimumAllowedValue') ? undefined : json['minimumAllowedValue'],
        'note': !(0, runtime_1.exists)(json, 'note') ? undefined : json['note'],
        'noteObject': !(0, runtime_1.exists)(json, 'noteObject') ? undefined : json['noteObject'],
        'noteHtml': !(0, runtime_1.exists)(json, 'noteHtml') ? undefined : json['noteHtml'],
        'originalUnitId': !(0, runtime_1.exists)(json, 'originalUnitId') ? undefined : json['originalUnitId'],
        'originalValue': !(0, runtime_1.exists)(json, 'originalValue') ? undefined : json['originalValue'],
        'pngPath': !(0, runtime_1.exists)(json, 'pngPath') ? undefined : json['pngPath'],
        'pngUrl': !(0, runtime_1.exists)(json, 'pngUrl') ? undefined : json['pngUrl'],
        'productUrl': !(0, runtime_1.exists)(json, 'productUrl') ? undefined : json['productUrl'],
        'sourceName': json['sourceName'],
        'startDate': !(0, runtime_1.exists)(json, 'startDate') ? undefined : json['startDate'],
        'startTimeEpoch': !(0, runtime_1.exists)(json, 'startTimeEpoch') ? undefined : json['startTimeEpoch'],
        'startTimeString': json['startTimeString'],
        'svgUrl': !(0, runtime_1.exists)(json, 'svgUrl') ? undefined : json['svgUrl'],
        'unitAbbreviatedName': json['unitAbbreviatedName'],
        'unitCategoryId': !(0, runtime_1.exists)(json, 'unitCategoryId') ? undefined : json['unitCategoryId'],
        'unitCategoryName': !(0, runtime_1.exists)(json, 'unitCategoryName') ? undefined : json['unitCategoryName'],
        'unitId': !(0, runtime_1.exists)(json, 'unitId') ? undefined : json['unitId'],
        'unitName': !(0, runtime_1.exists)(json, 'unitName') ? undefined : json['unitName'],
        'updatedAt': !(0, runtime_1.exists)(json, 'updatedAt') ? undefined : json['updatedAt'],
        'url': !(0, runtime_1.exists)(json, 'url') ? undefined : json['url'],
        'userVariableUnitAbbreviatedName': !(0, runtime_1.exists)(json, 'userVariableUnitAbbreviatedName') ? undefined : json['userVariableUnitAbbreviatedName'],
        'userVariableUnitCategoryId': !(0, runtime_1.exists)(json, 'userVariableUnitCategoryId') ? undefined : json['userVariableUnitCategoryId'],
        'userVariableUnitCategoryName': !(0, runtime_1.exists)(json, 'userVariableUnitCategoryName') ? undefined : json['userVariableUnitCategoryName'],
        'userVariableUnitId': !(0, runtime_1.exists)(json, 'userVariableUnitId') ? undefined : json['userVariableUnitId'],
        'userVariableUnitName': !(0, runtime_1.exists)(json, 'userVariableUnitName') ? undefined : json['userVariableUnitName'],
        'userVariableVariableCategoryId': !(0, runtime_1.exists)(json, 'userVariableVariableCategoryId') ? undefined : json['userVariableVariableCategoryId'],
        'userVariableVariableCategoryName': !(0, runtime_1.exists)(json, 'userVariableVariableCategoryName') ? undefined : json['userVariableVariableCategoryName'],
        'valence': !(0, runtime_1.exists)(json, 'valence') ? undefined : json['valence'],
        'value': json['value'],
        'variableCategoryId': !(0, runtime_1.exists)(json, 'variableCategoryId') ? undefined : json['variableCategoryId'],
        'variableCategoryImageUrl': !(0, runtime_1.exists)(json, 'variableCategoryImageUrl') ? undefined : json['variableCategoryImageUrl'],
        'variableCategoryName': !(0, runtime_1.exists)(json, 'variableCategoryName') ? undefined : json['variableCategoryName'],
        'variableDescription': !(0, runtime_1.exists)(json, 'variableDescription') ? undefined : json['variableDescription'],
        'variableId': !(0, runtime_1.exists)(json, 'variableId') ? undefined : json['variableId'],
        'variableName': json['variableName'],
        'displayName': !(0, runtime_1.exists)(json, 'displayName') ? undefined : json['displayName'],
    };
}
exports.MeasurementFromJSONTyped = MeasurementFromJSONTyped;
function MeasurementToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'card': (0, _1.CardToJSON)(value.card),
        'clientId': value.clientId,
        'connectorId': value.connectorId,
        'createdAt': value.createdAt,
        'displayValueAndUnitString': value.displayValueAndUnitString,
        'iconIcon': value.iconIcon,
        'id': value.id,
        'inputType': value.inputType,
        'ionIcon': value.ionIcon,
        'manualTracking': value.manualTracking,
        'maximumAllowedValue': value.maximumAllowedValue,
        'minimumAllowedValue': value.minimumAllowedValue,
        'note': value.note,
        'noteObject': value.noteObject,
        'noteHtml': value.noteHtml,
        'originalUnitId': value.originalUnitId,
        'originalValue': value.originalValue,
        'pngPath': value.pngPath,
        'pngUrl': value.pngUrl,
        'productUrl': value.productUrl,
        'sourceName': value.sourceName,
        'startDate': value.startDate,
        'startTimeEpoch': value.startTimeEpoch,
        'startTimeString': value.startTimeString,
        'svgUrl': value.svgUrl,
        'unitAbbreviatedName': value.unitAbbreviatedName,
        'unitCategoryId': value.unitCategoryId,
        'unitCategoryName': value.unitCategoryName,
        'unitId': value.unitId,
        'unitName': value.unitName,
        'updatedAt': value.updatedAt,
        'url': value.url,
        'userVariableUnitAbbreviatedName': value.userVariableUnitAbbreviatedName,
        'userVariableUnitCategoryId': value.userVariableUnitCategoryId,
        'userVariableUnitCategoryName': value.userVariableUnitCategoryName,
        'userVariableUnitId': value.userVariableUnitId,
        'userVariableUnitName': value.userVariableUnitName,
        'userVariableVariableCategoryId': value.userVariableVariableCategoryId,
        'userVariableVariableCategoryName': value.userVariableVariableCategoryName,
        'valence': value.valence,
        'value': value.value,
        'variableCategoryId': value.variableCategoryId,
        'variableCategoryImageUrl': value.variableCategoryImageUrl,
        'variableCategoryName': value.variableCategoryName,
        'variableDescription': value.variableDescription,
        'variableId': value.variableId,
        'variableName': value.variableName,
        'displayName': value.displayName,
    };
}
exports.MeasurementToJSON = MeasurementToJSON;
//# sourceMappingURL=Measurement.js.map