"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StudyChartsToJSON = exports.StudyChartsFromJSONTyped = exports.StudyChartsFromJSON = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
function StudyChartsFromJSON(json) {
    return StudyChartsFromJSONTyped(json, false);
}
exports.StudyChartsFromJSON = StudyChartsFromJSON;
function StudyChartsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'populationTraitScatterPlot': !(0, runtime_1.exists)(json, 'populationTraitScatterPlot') ? undefined : (0, _1.ChartFromJSON)(json['populationTraitScatterPlot']),
        'outcomeDistributionColumnChart': !(0, runtime_1.exists)(json, 'outcomeDistributionColumnChart') ? undefined : (0, _1.ChartFromJSON)(json['outcomeDistributionColumnChart']),
        'predictorDistributionColumnChart': !(0, runtime_1.exists)(json, 'predictorDistributionColumnChart') ? undefined : (0, _1.ChartFromJSON)(json['predictorDistributionColumnChart']),
        'correlationScatterPlot': !(0, runtime_1.exists)(json, 'correlationScatterPlot') ? undefined : (0, _1.ChartFromJSON)(json['correlationScatterPlot']),
        'pairsOverTimeLineChart': !(0, runtime_1.exists)(json, 'pairsOverTimeLineChart') ? undefined : (0, _1.ChartFromJSON)(json['pairsOverTimeLineChart']),
    };
}
exports.StudyChartsFromJSONTyped = StudyChartsFromJSONTyped;
function StudyChartsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'populationTraitScatterPlot': (0, _1.ChartToJSON)(value.populationTraitScatterPlot),
        'outcomeDistributionColumnChart': (0, _1.ChartToJSON)(value.outcomeDistributionColumnChart),
        'predictorDistributionColumnChart': (0, _1.ChartToJSON)(value.predictorDistributionColumnChart),
        'correlationScatterPlot': (0, _1.ChartToJSON)(value.correlationScatterPlot),
        'pairsOverTimeLineChart': (0, _1.ChartToJSON)(value.pairsOverTimeLineChart),
    };
}
exports.StudyChartsToJSON = StudyChartsToJSON;
//# sourceMappingURL=StudyCharts.js.map