version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/browsers:chrome67
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      #      - run:
      #          name: Running E2E tests with JUnit reporter
      #          command: npm run test:junit:staging
      #      - store_test_results:
      #          path: testReports
      #      - store_artifacts:
      #          path: coverage
      - run:
          when: always
          name: Copy cypress config
          command: cp cypress/config/cypress.staging.json cypress.json
      - run:
          when: always
          name: Run tests and generate mocha awesome report
          command: node_modules/gulp/bin/gulp.js cypress
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: mochareports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: src/slack/test
      - store_artifacts:
          path: cypress/reports/mocha