/**
 * Generated by @openapi-codegen
 *
 * @version 0.0.1
 */
export type AppVersionParam = string;

export type CauseUnitNameParam = string;

export type CauseVariableNameParam = string;

export type CauseVariableIdParam = number;

export type ClientIdParam = string;

export type ClientSecretParam = string;

export type ClientUserIdParam = number;

export type CodeParam = string;

export type ConnectorNameParam = string;

export type ConnectorNamePathParam =
  | "facebook"
  | "fitbit"
  | "github"
  | "googlecalendar"
  | "googlefit"
  | "medhelper"
  | "mint"
  | "moodpanda"
  | "moodscope"
  | "myfitnesspal"
  | "mynetdiary"
  | "netatmo"
  | "rescuetime"
  | "runkeeper"
  | "slack"
  | "sleepcloud"
  | "slice"
  | "up"
  | "whatpulse"
  | "withings"
  | "worldweatheronline"
  | "foursquare"
  | "strava"
  | "gmail";

export type CorrelationCoefficientParam = string;

export type CreatedParam = boolean;

export type DownVotedParam = boolean;

export type CreatedAtParam = string;

export type DoNotConvertParam = boolean;

export type DoNotProcessParam = boolean;

export type DurationOfActionParam = string;

export type EarliestMeasurementTimeParam = string;

export type EffectOrCauseParam = string;

export type EffectUnitNameParam = string;

export type EffectVariableNameParam = string;

export type EffectVariableIdParam = number;

export type ExactMatchParam = boolean;

export type GrantTypeParam = string;

export type GroupingTimezoneParam = string;

export type GroupingWidthParam = number;

export type IncludeAuthorizedClientsParam = boolean;

export type IncludeChartsParam = boolean;

export type IncludeDeletedParam = boolean;

export type IncludePrivateParam = boolean;

export type IncludePublicParam = boolean;

export type IncludeTagsParam = boolean;

export type JoinedParam = boolean;

export type LastSourceParam = string;

export type LatestMeasurementTimeParam = string;

/**
 * @default 100
 */
export type LimitParam = number;

export type Log = string;

export type ManualTrackingParam = boolean;

export type MinMaxFilterParam = boolean;

export type NumberOfRawMeasurementsParam = string;

/**
 * @minimum 0
 */
export type OffsetParam = number;

export type OnlyPastParam = boolean;

export type OnsetDelayParam = string;

export type OpenParam = boolean;

export type OutcomesOfInterestParam = boolean;

export type Platform = "chrome" | "android" | "ios" | "web";

export type AggregatedParam = boolean;

export type PrincipalInvestigatorUserIdParam = number;

export type PublicEffectOrCauseParam = string;

export type Pwd = string;

export type Recalculate = boolean;

export type RedirectUriParam = string;

export type ReminderTimeParam = string;

export type ResponseTypeParam = string;

export type ScopeParam = string;

export type SearchPhraseParam = string;

export type SortParam = string;

export type SourceNameParam = string;

export type StateParam = string;

export type StudyClientIdParam = string;

export type SynonymsParam = string;

export type TaggedVariableIdParam = number;

export type TagVariableIdParam = number;

export type UnitNameParam =
  | "% Recommended Daily Allowance"
  | "-4 to 4 Rating"
  | "0 to 1 Rating"
  | "0 to 5 Rating"
  | "1 to 10 Rating"
  | "1 to 5 Rating"
  | "Applications"
  | "Beats per Minute"
  | "Calories"
  | "Capsules"
  | "Centimeters"
  | "Count"
  | "Degrees Celsius"
  | "Degrees East"
  | "Degrees Fahrenheit"
  | "Degrees North"
  | "Dollars"
  | "Drops"
  | "Event"
  | "Feet"
  | "Grams"
  | "Hours"
  | "Inches"
  | "Index"
  | "Kilocalories"
  | "Kilograms"
  | "Kilometers"
  | "Liters"
  | "Meters"
  | "Micrograms"
  | "Micrograms per decilitre"
  | "Miles"
  | "Milligrams"
  | "Milliliters"
  | "Millimeters"
  | "Millimeters Merc"
  | "Milliseconds"
  | "Minutes"
  | "Pascal"
  | "Percent"
  | "Pieces"
  | "Pills"
  | "Pounds"
  | "Puffs"
  | "Seconds"
  | "Serving"
  | "Sprays"
  | "Tablets"
  | "Torr"
  | "Units"
  | "Yes/No"
  | "per Minute"
  | "Doses"
  | "Quarts"
  | "Ounces"
  | "International Units"
  | "Meters per Second";

export type UpdatedAtParam = string;

export type UserIdParam = number;

export type ValueParam = string;

export type VariableCategoryIdParam = number;

export type VariableIdParam = number;

export type VariableCategoryNameParam =
  | "Activities"
  | "Books"
  | "Causes of Illness"
  | "Cognitive Performance"
  | "Conditions"
  | "Emotions"
  | "Environment"
  | "Foods"
  | "Location"
  | "Miscellaneous"
  | "Movies and TV"
  | "Music"
  | "Nutrients"
  | "Payments"
  | "Physical Activity"
  | "Physique"
  | "Sleep"
  | "Social Interactions"
  | "Software"
  | "Symptoms"
  | "Treatments"
  | "Vital Signs"
  | "Goals";

export type VariableNameParam = string;

export type ConciseParam = boolean;
