"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppSettingsToJSON = exports.AppSettingsFromJSONTyped = exports.AppSettingsFromJSON = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
function AppSettingsFromJSON(json) {
    return AppSettingsFromJSONTyped(json, false);
}
exports.AppSettingsFromJSON = AppSettingsFromJSON;
function AppSettingsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'additionalSettings': !(0, runtime_1.exists)(json, 'additionalSettings') ? undefined : json['additionalSettings'],
        'appDescription': !(0, runtime_1.exists)(json, 'appDescription') ? undefined : json['appDescription'],
        'appDesign': !(0, runtime_1.exists)(json, 'appDesign') ? undefined : json['appDesign'],
        'appDisplayName': !(0, runtime_1.exists)(json, 'appDisplayName') ? undefined : json['appDisplayName'],
        'appStatus': !(0, runtime_1.exists)(json, 'appStatus') ? undefined : json['appStatus'],
        'appType': !(0, runtime_1.exists)(json, 'appType') ? undefined : json['appType'],
        'buildEnabled': !(0, runtime_1.exists)(json, 'buildEnabled') ? undefined : json['buildEnabled'],
        'clientId': !(0, runtime_1.exists)(json, 'clientId') ? undefined : json['clientId'],
        'clientSecret': !(0, runtime_1.exists)(json, 'clientSecret') ? undefined : json['clientSecret'],
        'collaborators': !(0, runtime_1.exists)(json, 'collaborators') ? undefined : (json['collaborators'].map(_1.UserFromJSON)),
        'createdAt': !(0, runtime_1.exists)(json, 'createdAt') ? undefined : json['createdAt'],
        'userId': !(0, runtime_1.exists)(json, 'userId') ? undefined : json['userId'],
        'users': !(0, runtime_1.exists)(json, 'users') ? undefined : (json['users'].map(_1.UserFromJSON)),
        'redirectUri': !(0, runtime_1.exists)(json, 'redirectUri') ? undefined : json['redirectUri'],
        'companyName': !(0, runtime_1.exists)(json, 'companyName') ? undefined : json['companyName'],
        'homepageUrl': !(0, runtime_1.exists)(json, 'homepageUrl') ? undefined : json['homepageUrl'],
        'iconUrl': !(0, runtime_1.exists)(json, 'iconUrl') ? undefined : json['iconUrl'],
        'longDescription': !(0, runtime_1.exists)(json, 'longDescription') ? undefined : json['longDescription'],
        'splashScreen': !(0, runtime_1.exists)(json, 'splashScreen') ? undefined : json['splashScreen'],
        'textLogo': !(0, runtime_1.exists)(json, 'textLogo') ? undefined : json['textLogo'],
    };
}
exports.AppSettingsFromJSONTyped = AppSettingsFromJSONTyped;
function AppSettingsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'additionalSettings': value.additionalSettings,
        'appDescription': value.appDescription,
        'appDesign': value.appDesign,
        'appDisplayName': value.appDisplayName,
        'appStatus': value.appStatus,
        'appType': value.appType,
        'buildEnabled': value.buildEnabled,
        'clientId': value.clientId,
        'clientSecret': value.clientSecret,
        'collaborators': value.collaborators === undefined ? undefined : (value.collaborators.map(_1.UserToJSON)),
        'createdAt': value.createdAt,
        'userId': value.userId,
        'users': value.users === undefined ? undefined : (value.users.map(_1.UserToJSON)),
        'redirectUri': value.redirectUri,
        'companyName': value.companyName,
        'homepageUrl': value.homepageUrl,
        'iconUrl': value.iconUrl,
        'longDescription': value.longDescription,
        'splashScreen': value.splashScreen,
        'textLogo': value.textLogo,
    };
}
exports.AppSettingsToJSON = AppSettingsToJSON;
//# sourceMappingURL=AppSettings.js.map