"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChartToJSON = exports.ChartFromJSONTyped = exports.ChartFromJSON = void 0;
var runtime_1 = require("../runtime");
function ChartFromJSON(json) {
    return ChartFromJSONTyped(json, false);
}
exports.ChartFromJSON = ChartFromJSON;
function ChartFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'highchartConfig': !(0, runtime_1.exists)(json, 'highchartConfig') ? undefined : json['highchartConfig'],
        'chartId': !(0, runtime_1.exists)(json, 'chartId') ? undefined : json['chartId'],
        'chartTitle': !(0, runtime_1.exists)(json, 'chartTitle') ? undefined : json['chartTitle'],
        'explanation': !(0, runtime_1.exists)(json, 'explanation') ? undefined : json['explanation'],
        'svgUrl': !(0, runtime_1.exists)(json, 'svgUrl') ? undefined : json['svgUrl'],
        'svg': !(0, runtime_1.exists)(json, 'svg') ? undefined : json['svg'],
    };
}
exports.ChartFromJSONTyped = ChartFromJSONTyped;
function ChartToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'highchartConfig': value.highchartConfig,
        'chartId': value.chartId,
        'chartTitle': value.chartTitle,
        'explanation': value.explanation,
        'svgUrl': value.svgUrl,
        'svg': value.svg,
    };
}
exports.ChartToJSON = ChartToJSON;
//# sourceMappingURL=Chart.js.map
