"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConnectInstructionsToJSON = exports.ConnectInstructionsFromJSONTyped = exports.ConnectInstructionsFromJSON = void 0;
var runtime_1 = require("../runtime");
function ConnectInstructionsFromJSON(json) {
    return ConnectInstructionsFromJSONTyped(json, false);
}
exports.ConnectInstructionsFromJSON = ConnectInstructionsFromJSON;
function ConnectInstructionsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'parameters': !(0, runtime_1.exists)(json, 'parameters') ? undefined : json['parameters'],
        'url': json['url'],
        'usePopup': !(0, runtime_1.exists)(json, 'usePopup') ? undefined : json['usePopup'],
    };
}
exports.ConnectInstructionsFromJSONTyped = ConnectInstructionsFromJSONTyped;
function ConnectInstructionsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'parameters': value.parameters,
        'url': value.url,
        'usePopup': value.usePopup,
    };
}
exports.ConnectInstructionsToJSON = ConnectInstructionsToJSON;
//# sourceMappingURL=ConnectInstructions.js.map
