"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConversionStepToJSON = exports.ConversionStepFromJSONTyped = exports.ConversionStepFromJSON = exports.ConversionStepOperationEnum = void 0;
/**
* @export
* @enum {string}
*/
var ConversionStepOperationEnum;
(function (ConversionStepOperationEnum) {
    ConversionStepOperationEnum["Add"] = "ADD";
    ConversionStepOperationEnum["Multiply"] = "MULTIPLY";
})(ConversionStepOperationEnum = exports.ConversionStepOperationEnum || (exports.ConversionStepOperationEnum = {}));
function ConversionStepFromJSON(json) {
    return ConversionStepFromJSONTyped(json, false);
}
exports.ConversionStepFromJSON = ConversionStepFromJSON;
function ConversionStepFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'operation': json['operation'],
        'value': json['value'],
    };
}
exports.ConversionStepFromJSONTyped = ConversionStepFromJSONTyped;
function ConversionStepToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'operation': value.operation,
        'value': value.value,
    };
}
exports.ConversionStepToJSON = ConversionStepToJSON;
//# sourceMappingURL=ConversionStep.js.map
