"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataSourceToJSON = exports.DataSourceFromJSONTyped = exports.DataSourceFromJSON = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
function DataSourceFromJSON(json) {
    return DataSourceFromJSONTyped(json, false);
}
exports.DataSourceFromJSON = DataSourceFromJSON;
function DataSourceFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'affiliate': json['affiliate'],
        'backgroundColor': !(0, runtime_1.exists)(json, 'backgroundColor') ? undefined : json['backgroundColor'],
        'buttons': !(0, runtime_1.exists)(json, 'buttons') ? undefined : (json['buttons'].map(_1.ButtonFromJSON)),
        'card': !(0, runtime_1.exists)(json, 'card') ? undefined : (0, _1.CardFromJSON)(json['card']),
        'clientId': !(0, runtime_1.exists)(json, 'clientId') ? undefined : json['clientId'],
        'connected': !(0, runtime_1.exists)(json, 'connected') ? undefined : json['connected'],
        'connectError': !(0, runtime_1.exists)(json, 'connectError') ? undefined : json['connectError'],
        'connectInstructions': !(0, runtime_1.exists)(json, 'connectInstructions') ? undefined : (0, _1.ConnectInstructionsFromJSON)(json['connectInstructions']),
        'connectorId': !(0, runtime_1.exists)(json, 'connectorId') ? undefined : json['connectorId'],
        'connectStatus': !(0, runtime_1.exists)(json, 'connectStatus') ? undefined : json['connectStatus'],
        'count': !(0, runtime_1.exists)(json, 'count') ? undefined : json['count'],
        'createdAt': !(0, runtime_1.exists)(json, 'createdAt') ? undefined : json['createdAt'],
        'connectorClientId': json['connectorClientId'],
        'defaultVariableCategoryName': json['defaultVariableCategoryName'],
        'displayName': json['displayName'],
        'enabled': json['enabled'],
        'getItUrl': json['getItUrl'],
        'id': json['id'],
        'image': json['image'],
        'imageHtml': json['imageHtml'],
        'lastSuccessfulUpdatedAt': !(0, runtime_1.exists)(json, 'lastSuccessfulUpdatedAt') ? undefined : json['lastSuccessfulUpdatedAt'],
        'lastUpdate': !(0, runtime_1.exists)(json, 'lastUpdate') ? undefined : json['lastUpdate'],
        'linkedDisplayNameHtml': json['linkedDisplayNameHtml'],
        'longDescription': json['longDescription'],
        'message': !(0, runtime_1.exists)(json, 'message') ? undefined : json['message'],
        'mobileConnectMethod': !(0, runtime_1.exists)(json, 'mobileConnectMethod') ? undefined : json['mobileConnectMethod'],
        'name': json['name'],
        'platforms': !(0, runtime_1.exists)(json, 'platforms') ? undefined : json['platforms'],
        'premium': !(0, runtime_1.exists)(json, 'premium') ? undefined : json['premium'],
        'scopes': !(0, runtime_1.exists)(json, 'scopes') ? undefined : json['scopes'],
        'shortDescription': json['shortDescription'],
        'spreadsheetUploadLink': !(0, runtime_1.exists)(json, 'spreadsheetUploadLink') ? undefined : json['spreadsheetUploadLink'],
        'totalMeasurementsInLastUpdate': !(0, runtime_1.exists)(json, 'totalMeasurementsInLastUpdate') ? undefined : json['totalMeasurementsInLastUpdate'],
        'updatedAt': !(0, runtime_1.exists)(json, 'updatedAt') ? undefined : json['updatedAt'],
        'updateRequestedAt': !(0, runtime_1.exists)(json, 'updateRequestedAt') ? undefined : json['updateRequestedAt'],
        'updateStatus': !(0, runtime_1.exists)(json, 'updateStatus') ? undefined : json['updateStatus'],
        'userId': !(0, runtime_1.exists)(json, 'userId') ? undefined : json['userId'],
    };
}
exports.DataSourceFromJSONTyped = DataSourceFromJSONTyped;
function DataSourceToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'affiliate': value.affiliate,
        'backgroundColor': value.backgroundColor,
        'buttons': value.buttons === undefined ? undefined : (value.buttons.map(_1.ButtonToJSON)),
        'card': (0, _1.CardToJSON)(value.card),
        'clientId': value.clientId,
        'connected': value.connected,
        'connectError': value.connectError,
        'connectInstructions': (0, _1.ConnectInstructionsToJSON)(value.connectInstructions),
        'connectorId': value.connectorId,
        'connectStatus': value.connectStatus,
        'count': value.count,
        'createdAt': value.createdAt,
        'connectorClientId': value.connectorClientId,
        'defaultVariableCategoryName': value.defaultVariableCategoryName,
        'displayName': value.displayName,
        'enabled': value.enabled,
        'getItUrl': value.getItUrl,
        'id': value.id,
        'image': value.image,
        'imageHtml': value.imageHtml,
        'lastSuccessfulUpdatedAt': value.lastSuccessfulUpdatedAt,
        'lastUpdate': value.lastUpdate,
        'linkedDisplayNameHtml': value.linkedDisplayNameHtml,
        'longDescription': value.longDescription,
        'message': value.message,
        'mobileConnectMethod': value.mobileConnectMethod,
        'name': value.name,
        'platforms': value.platforms,
        'premium': value.premium,
        'scopes': value.scopes,
        'shortDescription': value.shortDescription,
        'spreadsheetUploadLink': value.spreadsheetUploadLink,
        'totalMeasurementsInLastUpdate': value.totalMeasurementsInLastUpdate,
        'updatedAt': value.updatedAt,
        'updateRequestedAt': value.updateRequestedAt,
        'updateStatus': value.updateStatus,
        'userId': value.userId,
    };
}
exports.DataSourceToJSON = DataSourceToJSON;
//# sourceMappingURL=DataSource.js.map
