"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeviceTokenToJSON = exports.DeviceTokenFromJSONTyped = exports.DeviceTokenFromJSON = void 0;
var runtime_1 = require("../runtime");
function DeviceTokenFromJSON(json) {
    return DeviceTokenFromJSONTyped(json, false);
}
exports.DeviceTokenFromJSON = DeviceTokenFromJSON;
function DeviceTokenFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'clientId': !(0, runtime_1.exists)(json, 'clientId') ? undefined : json['clientId'],
        'platform': json['platform'],
        'deviceToken': json['deviceToken'],
    };
}
exports.DeviceTokenFromJSONTyped = DeviceTokenFromJSONTyped;
function DeviceTokenToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'clientId': value.clientId,
        'platform': value.platform,
        'deviceToken': value.deviceToken,
    };
}
exports.DeviceTokenToJSON = DeviceTokenToJSON;
//# sourceMappingURL=DeviceToken.js.map