"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExplanationToJSON = exports.ExplanationFromJSONTyped = exports.ExplanationFromJSON = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
function ExplanationFromJSON(json) {
    return ExplanationFromJSONTyped(json, false);
}
exports.ExplanationFromJSON = ExplanationFromJSON;
function ExplanationFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'description': json['description'],
        'image': (0, _1.ImageFromJSON)(json['image']),
        'ionIcon': json['ionIcon'],
        'startTracking': (0, _1.ExplanationStartTrackingFromJSON)(json['startTracking']),
        'title': json['title'],
        'html': !(0, runtime_1.exists)(json, 'html') ? undefined : json['html'],
    };
}
exports.ExplanationFromJSONTyped = ExplanationFromJSONTyped;
function ExplanationToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'description': value.description,
        'image': (0, _1.ImageToJSON)(value.image),
        'ionIcon': value.ionIcon,
        'startTracking': (0, _1.ExplanationStartTrackingToJSON)(value.startTracking),
        'title': value.title,
        'html': value.html,
    };
}
exports.ExplanationToJSON = ExplanationToJSON;
//# sourceMappingURL=Explanation.js.map