"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetSharesResponseToJSON = exports.GetSharesResponseFromJSONTyped = exports.GetSharesResponseFromJSON = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
function GetSharesResponseFromJSON(json) {
    return GetSharesResponseFromJSONTyped(json, false);
}
exports.GetSharesResponseFromJSON = GetSharesResponseFromJSON;
function GetSharesResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'authorizedClients': !(0, runtime_1.exists)(json, 'authorizedClients') ? undefined : (0, _1.AuthorizedClientsFromJSON)(json['authorizedClients']),
        'description': json['description'],
        'summary': json['summary'],
        'errors': !(0, runtime_1.exists)(json, 'errors') ? undefined : (json['errors'].map(_1.ErrorResponseFromJSON)),
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
        'success': !(0, runtime_1.exists)(json, 'success') ? undefined : json['success'],
        'code': !(0, runtime_1.exists)(json, 'code') ? undefined : json['code'],
        'link': !(0, runtime_1.exists)(json, 'link') ? undefined : json['link'],
        'card': !(0, runtime_1.exists)(json, 'card') ? undefined : (0, _1.CardFromJSON)(json['card']),
    };
}
exports.GetSharesResponseFromJSONTyped = GetSharesResponseFromJSONTyped;
function GetSharesResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'authorizedClients': (0, _1.AuthorizedClientsToJSON)(value.authorizedClients),
        'description': value.description,
        'summary': value.summary,
        'errors': value.errors === undefined ? undefined : (value.errors.map(_1.ErrorResponseToJSON)),
        'status': value.status,
        'success': value.success,
        'code': value.code,
        'link': value.link,
        'card': (0, _1.CardToJSON)(value.card),
    };
}
exports.GetSharesResponseToJSON = GetSharesResponseToJSON;
//# sourceMappingURL=GetSharesResponse.js.map
