/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * Ex: 240
     * @type {string}
     * @memberof Image
     */
    height: string;
    /**
     * Ex: https://www.filepicker.io/api/file/TjmeNWS5Q2SFmtJlUGLf
     * @type {string}
     * @memberof Image
     */
    imageUrl: string;
    /**
     * Ex: 224
     * @type {string}
     * @memberof Image
     */
    width: string;
}

export function ImageFromJSON(json: any): Image {
    return ImageFromJSONTyped(json, false);
}

export function ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Image {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'height': json['height'],
        'imageUrl': json['imageUrl'],
        'width': json['width'],
    };
}

export function ImageToJSON(value?: Image | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'height': value.height,
        'imageUrl': value.imageUrl,
        'width': value.width,
    };
}


