"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MeasurementSetToJSON = exports.MeasurementSetFromJSONTyped = exports.MeasurementSetFromJSON = exports.MeasurementSetVariableCategoryNameEnum = exports.MeasurementSetCombinationOperationEnum = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
/**
* @export
* @enum {string}
*/
var MeasurementSetCombinationOperationEnum;
(function (MeasurementSetCombinationOperationEnum) {
    MeasurementSetCombinationOperationEnum["Mean"] = "MEAN";
    MeasurementSetCombinationOperationEnum["Sum"] = "SUM";
})(MeasurementSetCombinationOperationEnum = exports.MeasurementSetCombinationOperationEnum || (exports.MeasurementSetCombinationOperationEnum = {})); /**
* @export
* @enum {string}
*/
var MeasurementSetVariableCategoryNameEnum;
(function (MeasurementSetVariableCategoryNameEnum) {
    MeasurementSetVariableCategoryNameEnum["Activity"] = "Activity";
    MeasurementSetVariableCategoryNameEnum["Books"] = "Books";
    MeasurementSetVariableCategoryNameEnum["CausesOfIllness"] = "Causes of Illness";
    MeasurementSetVariableCategoryNameEnum["CognitivePerformance"] = "Cognitive Performance";
    MeasurementSetVariableCategoryNameEnum["Conditions"] = "Conditions";
    MeasurementSetVariableCategoryNameEnum["Emotions"] = "Emotions";
    MeasurementSetVariableCategoryNameEnum["Environment"] = "Environment";
    MeasurementSetVariableCategoryNameEnum["Foods"] = "Foods";
    MeasurementSetVariableCategoryNameEnum["Goals"] = "Goals";
    MeasurementSetVariableCategoryNameEnum["Locations"] = "Locations";
    MeasurementSetVariableCategoryNameEnum["Miscellaneous"] = "Miscellaneous";
    MeasurementSetVariableCategoryNameEnum["MoviesAndTv"] = "Movies and TV";
    MeasurementSetVariableCategoryNameEnum["Music"] = "Music";
    MeasurementSetVariableCategoryNameEnum["Nutrients"] = "Nutrients";
    MeasurementSetVariableCategoryNameEnum["Payments"] = "Payments";
    MeasurementSetVariableCategoryNameEnum["PhysicalActivities"] = "Physical Activities";
    MeasurementSetVariableCategoryNameEnum["Physique"] = "Physique";
    MeasurementSetVariableCategoryNameEnum["Sleep"] = "Sleep";
    MeasurementSetVariableCategoryNameEnum["SocialInteractions"] = "Social Interactions";
    MeasurementSetVariableCategoryNameEnum["Software"] = "Software";
    MeasurementSetVariableCategoryNameEnum["Symptoms"] = "Symptoms";
    MeasurementSetVariableCategoryNameEnum["Treatments"] = "Treatments";
    MeasurementSetVariableCategoryNameEnum["VitalSigns"] = "Vital Signs";
})(MeasurementSetVariableCategoryNameEnum = exports.MeasurementSetVariableCategoryNameEnum || (exports.MeasurementSetVariableCategoryNameEnum = {}));
function MeasurementSetFromJSON(json) {
    return MeasurementSetFromJSONTyped(json, false);
}
exports.MeasurementSetFromJSON = MeasurementSetFromJSON;
function MeasurementSetFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'combinationOperation': !(0, runtime_1.exists)(json, 'combinationOperation') ? undefined : json['combinationOperation'],
        'measurementItems': (json['measurementItems'].map(_1.MeasurementItemFromJSON)),
        'sourceName': json['sourceName'],
        'unitAbbreviatedName': json['unitAbbreviatedName'],
        'variableCategoryName': !(0, runtime_1.exists)(json, 'variableCategoryName') ? undefined : json['variableCategoryName'],
        'variableName': json['variableName'],
        'upc': !(0, runtime_1.exists)(json, 'upc') ? undefined : json['upc'],
    };
}
exports.MeasurementSetFromJSONTyped = MeasurementSetFromJSONTyped;
function MeasurementSetToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'combinationOperation': value.combinationOperation,
        'measurementItems': (value.measurementItems.map(_1.MeasurementItemToJSON)),
        'sourceName': value.sourceName,
        'unitAbbreviatedName': value.unitAbbreviatedName,
        'variableCategoryName': value.variableCategoryName,
        'variableName': value.variableName,
        'upc': value.upc,
    };
}
exports.MeasurementSetToJSON = MeasurementSetToJSON;
//# sourceMappingURL=MeasurementSet.js.map
