/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MeasurementItem
 */
export interface MeasurementItem {
    /**
     * Optional note to include with the measurement
     * @type {string}
     * @memberof MeasurementItem
     */
    note?: string;
    /**
     * Timestamp for the measurement event in epoch time (unixtime)
     * @type {number}
     * @memberof MeasurementItem
     */
    timestamp: number;
    /**
     * Measurement value
     * @type {number}
     * @memberof MeasurementItem
     */
    value: number;
}

export function MeasurementItemFromJSON(json: any): MeasurementItem {
    return MeasurementItemFromJSONTyped(json, false);
}

export function MeasurementItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'note': !exists(json, 'note') ? undefined : json['note'],
        'timestamp': json['timestamp'],
        'value': json['value'],
    };
}

export function MeasurementItemToJSON(value?: MeasurementItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'note': value.note,
        'timestamp': value.timestamp,
        'value': value.value,
    };
}


