"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostTrackingRemindersDataResponseToJSON = exports.PostTrackingRemindersDataResponseFromJSONTyped = exports.PostTrackingRemindersDataResponseFromJSON = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
function PostTrackingRemindersDataResponseFromJSON(json) {
    return PostTrackingRemindersDataResponseFromJSONTyped(json, false);
}
exports.PostTrackingRemindersDataResponseFromJSON = PostTrackingRemindersDataResponseFromJSON;
function PostTrackingRemindersDataResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'trackingReminderNotifications': !(0, runtime_1.exists)(json, 'trackingReminderNotifications') ? undefined : (json['trackingReminderNotifications'].map(_1.TrackingReminderNotificationFromJSON)),
        'trackingReminders': !(0, runtime_1.exists)(json, 'trackingReminders') ? undefined : (json['trackingReminders'].map(_1.TrackingReminderFromJSON)),
        'userVariables': !(0, runtime_1.exists)(json, 'userVariables') ? undefined : (json['userVariables'].map(_1.VariableFromJSON)),
        'description': !(0, runtime_1.exists)(json, 'description') ? undefined : json['description'],
        'summary': !(0, runtime_1.exists)(json, 'summary') ? undefined : json['summary'],
        'errors': !(0, runtime_1.exists)(json, 'errors') ? undefined : (json['errors'].map(_1.ErrorResponseFromJSON)),
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
        'success': !(0, runtime_1.exists)(json, 'success') ? undefined : json['success'],
        'code': !(0, runtime_1.exists)(json, 'code') ? undefined : json['code'],
        'link': !(0, runtime_1.exists)(json, 'link') ? undefined : json['link'],
        'card': !(0, runtime_1.exists)(json, 'card') ? undefined : (0, _1.CardFromJSON)(json['card']),
    };
}
exports.PostTrackingRemindersDataResponseFromJSONTyped = PostTrackingRemindersDataResponseFromJSONTyped;
function PostTrackingRemindersDataResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'trackingReminderNotifications': value.trackingReminderNotifications === undefined ? undefined : (value.trackingReminderNotifications.map(_1.TrackingReminderNotificationToJSON)),
        'trackingReminders': value.trackingReminders === undefined ? undefined : (value.trackingReminders.map(_1.TrackingReminderToJSON)),
        'userVariables': value.userVariables === undefined ? undefined : (value.userVariables.map(_1.VariableToJSON)),
        'description': value.description,
        'summary': value.summary,
        'errors': value.errors === undefined ? undefined : (value.errors.map(_1.ErrorResponseToJSON)),
        'status': value.status,
        'success': value.success,
        'code': value.code,
        'link': value.link,
        'card': (0, _1.CardToJSON)(value.card),
    };
}
exports.PostTrackingRemindersDataResponseToJSON = PostTrackingRemindersDataResponseToJSON;
//# sourceMappingURL=PostTrackingRemindersDataResponse.js.map
