"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StudySharingToJSON = exports.StudySharingFromJSONTyped = exports.StudySharingFromJSON = void 0;
function StudySharingFromJSON(json) {
    return StudySharingFromJSONTyped(json, false);
}
exports.StudySharingFromJSON = StudySharingFromJSON;
function StudySharingFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'shareUserMeasurements': json['shareUserMeasurements'],
        'sharingDescription': json['sharingDescription'],
        'sharingTitle': json['sharingTitle'],
    };
}
exports.StudySharingFromJSONTyped = StudySharingFromJSONTyped;
function StudySharingToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'shareUserMeasurements': value.shareUserMeasurements,
        'sharingDescription': value.sharingDescription,
        'sharingTitle': value.sharingTitle,
    };
}
exports.StudySharingToJSON = StudySharingToJSON;
//# sourceMappingURL=StudySharing.js.map