"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StudyToJSON = exports.StudyFromJSONTyped = exports.StudyFromJSON = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
function StudyFromJSON(json) {
    return StudyFromJSONTyped(json, false);
}
exports.StudyFromJSON = StudyFromJSON;
function StudyFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'type': json['type'],
        'userId': !(0, runtime_1.exists)(json, 'userId') ? undefined : json['userId'],
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'causeVariable': !(0, runtime_1.exists)(json, 'causeVariable') ? undefined : (0, _1.VariableFromJSON)(json['causeVariable']),
        'causeVariableName': !(0, runtime_1.exists)(json, 'causeVariableName') ? undefined : json['causeVariableName'],
        'studyCharts': !(0, runtime_1.exists)(json, 'studyCharts') ? undefined : (0, _1.StudyChartsFromJSON)(json['studyCharts']),
        'effectVariable': !(0, runtime_1.exists)(json, 'effectVariable') ? undefined : (0, _1.VariableFromJSON)(json['effectVariable']),
        'effectVariableName': !(0, runtime_1.exists)(json, 'effectVariableName') ? undefined : json['effectVariableName'],
        'participantInstructions': !(0, runtime_1.exists)(json, 'participantInstructions') ? undefined : (0, _1.ParticipantInstructionFromJSON)(json['participantInstructions']),
        'statistics': !(0, runtime_1.exists)(json, 'statistics') ? undefined : (0, _1.CorrelationFromJSON)(json['statistics']),
        'studyCard': !(0, runtime_1.exists)(json, 'studyCard') ? undefined : (0, _1.CardFromJSON)(json['studyCard']),
        'studyHtml': !(0, runtime_1.exists)(json, 'studyHtml') ? undefined : (0, _1.StudyHtmlFromJSON)(json['studyHtml']),
        'studyImages': !(0, runtime_1.exists)(json, 'studyImages') ? undefined : (0, _1.StudyImagesFromJSON)(json['studyImages']),
        'studyLinks': !(0, runtime_1.exists)(json, 'studyLinks') ? undefined : (0, _1.StudyLinksFromJSON)(json['studyLinks']),
        'studySharing': !(0, runtime_1.exists)(json, 'studySharing') ? undefined : (0, _1.StudySharingFromJSON)(json['studySharing']),
        'studyText': !(0, runtime_1.exists)(json, 'studyText') ? undefined : (0, _1.StudyTextFromJSON)(json['studyText']),
        'studyVotes': !(0, runtime_1.exists)(json, 'studyVotes') ? undefined : (0, _1.StudyVotesFromJSON)(json['studyVotes']),
        'joined': !(0, runtime_1.exists)(json, 'joined') ? undefined : json['joined'],
    };
}
exports.StudyFromJSONTyped = StudyFromJSONTyped;
function StudyToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'type': value.type,
        'userId': value.userId,
        'id': value.id,
        'causeVariable': (0, _1.VariableToJSON)(value.causeVariable),
        'causeVariableName': value.causeVariableName,
        'studyCharts': (0, _1.StudyChartsToJSON)(value.studyCharts),
        'effectVariable': (0, _1.VariableToJSON)(value.effectVariable),
        'effectVariableName': value.effectVariableName,
        'participantInstructions': (0, _1.ParticipantInstructionToJSON)(value.participantInstructions),
        'statistics': (0, _1.CorrelationToJSON)(value.statistics),
        'studyCard': (0, _1.CardToJSON)(value.studyCard),
        'studyHtml': (0, _1.StudyHtmlToJSON)(value.studyHtml),
        'studyImages': (0, _1.StudyImagesToJSON)(value.studyImages),
        'studyLinks': (0, _1.StudyLinksToJSON)(value.studyLinks),
        'studySharing': (0, _1.StudySharingToJSON)(value.studySharing),
        'studyText': (0, _1.StudyTextToJSON)(value.studyText),
        'studyVotes': (0, _1.StudyVotesToJSON)(value.studyVotes),
        'joined': value.joined,
    };
}
exports.StudyToJSON = StudyToJSON;
//# sourceMappingURL=Study.js.map