/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Chart,
    ChartFromJSON,
    ChartFromJSONTyped,
    ChartToJSON,
} from './';

/**
 * An object with various chart properties each property contain and svg and Highcharts configuration
 * @export
 * @interface StudyCharts
 */
export interface StudyCharts {
    /**
     * 
     * @type {Chart}
     * @memberof StudyCharts
     */
    populationTraitScatterPlot?: Chart;
    /**
     * 
     * @type {Chart}
     * @memberof StudyCharts
     */
    outcomeDistributionColumnChart?: Chart;
    /**
     * 
     * @type {Chart}
     * @memberof StudyCharts
     */
    predictorDistributionColumnChart?: Chart;
    /**
     * 
     * @type {Chart}
     * @memberof StudyCharts
     */
    correlationScatterPlot?: Chart;
    /**
     * 
     * @type {Chart}
     * @memberof StudyCharts
     */
    pairsOverTimeLineChart?: Chart;
}

export function StudyChartsFromJSON(json: any): StudyCharts {
    return StudyChartsFromJSONTyped(json, false);
}

export function StudyChartsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudyCharts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'populationTraitScatterPlot': !exists(json, 'populationTraitScatterPlot') ? undefined : ChartFromJSON(json['populationTraitScatterPlot']),
        'outcomeDistributionColumnChart': !exists(json, 'outcomeDistributionColumnChart') ? undefined : ChartFromJSON(json['outcomeDistributionColumnChart']),
        'predictorDistributionColumnChart': !exists(json, 'predictorDistributionColumnChart') ? undefined : ChartFromJSON(json['predictorDistributionColumnChart']),
        'correlationScatterPlot': !exists(json, 'correlationScatterPlot') ? undefined : ChartFromJSON(json['correlationScatterPlot']),
        'pairsOverTimeLineChart': !exists(json, 'pairsOverTimeLineChart') ? undefined : ChartFromJSON(json['pairsOverTimeLineChart']),
    };
}

export function StudyChartsToJSON(value?: StudyCharts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'populationTraitScatterPlot': ChartToJSON(value.populationTraitScatterPlot),
        'outcomeDistributionColumnChart': ChartToJSON(value.outcomeDistributionColumnChart),
        'predictorDistributionColumnChart': ChartToJSON(value.predictorDistributionColumnChart),
        'correlationScatterPlot': ChartToJSON(value.correlationScatterPlot),
        'pairsOverTimeLineChart': ChartToJSON(value.pairsOverTimeLineChart),
    };
}


