"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrackingReminderToJSON = exports.TrackingReminderFromJSONTyped = exports.TrackingReminderFromJSON = exports.TrackingReminderVariableCategoryNameEnum = exports.TrackingReminderCombinationOperationEnum = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
/**
* @export
* @enum {string}
*/
var TrackingReminderCombinationOperationEnum;
(function (TrackingReminderCombinationOperationEnum) {
    TrackingReminderCombinationOperationEnum["Mean"] = "MEAN";
    TrackingReminderCombinationOperationEnum["Sum"] = "SUM";
})(TrackingReminderCombinationOperationEnum = exports.TrackingReminderCombinationOperationEnum || (exports.TrackingReminderCombinationOperationEnum = {})); /**
* @export
* @enum {string}
*/
var TrackingReminderVariableCategoryNameEnum;
(function (TrackingReminderVariableCategoryNameEnum) {
    TrackingReminderVariableCategoryNameEnum["Activity"] = "Activity";
    TrackingReminderVariableCategoryNameEnum["Books"] = "Books";
    TrackingReminderVariableCategoryNameEnum["CausesOfIllness"] = "Causes of Illness";
    TrackingReminderVariableCategoryNameEnum["CognitivePerformance"] = "Cognitive Performance";
    TrackingReminderVariableCategoryNameEnum["Conditions"] = "Conditions";
    TrackingReminderVariableCategoryNameEnum["Emotions"] = "Emotions";
    TrackingReminderVariableCategoryNameEnum["Environment"] = "Environment";
    TrackingReminderVariableCategoryNameEnum["Foods"] = "Foods";
    TrackingReminderVariableCategoryNameEnum["Goals"] = "Goals";
    TrackingReminderVariableCategoryNameEnum["Locations"] = "Locations";
    TrackingReminderVariableCategoryNameEnum["Miscellaneous"] = "Miscellaneous";
    TrackingReminderVariableCategoryNameEnum["MoviesAndTv"] = "Movies and TV";
    TrackingReminderVariableCategoryNameEnum["Music"] = "Music";
    TrackingReminderVariableCategoryNameEnum["Nutrients"] = "Nutrients";
    TrackingReminderVariableCategoryNameEnum["Payments"] = "Payments";
    TrackingReminderVariableCategoryNameEnum["PhysicalActivities"] = "Physical Activities";
    TrackingReminderVariableCategoryNameEnum["Physique"] = "Physique";
    TrackingReminderVariableCategoryNameEnum["Sleep"] = "Sleep";
    TrackingReminderVariableCategoryNameEnum["SocialInteractions"] = "Social Interactions";
    TrackingReminderVariableCategoryNameEnum["Software"] = "Software";
    TrackingReminderVariableCategoryNameEnum["Symptoms"] = "Symptoms";
    TrackingReminderVariableCategoryNameEnum["Treatments"] = "Treatments";
    TrackingReminderVariableCategoryNameEnum["VitalSigns"] = "Vital Signs";
})(TrackingReminderVariableCategoryNameEnum = exports.TrackingReminderVariableCategoryNameEnum || (exports.TrackingReminderVariableCategoryNameEnum = {}));
function TrackingReminderFromJSON(json) {
    return TrackingReminderFromJSONTyped(json, false);
}
exports.TrackingReminderFromJSON = TrackingReminderFromJSON;
function TrackingReminderFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'actionArray': !(0, runtime_1.exists)(json, 'actionArray') ? undefined : (json['actionArray'].map(_1.TrackingReminderNotificationActionFromJSON)),
        'availableUnits': !(0, runtime_1.exists)(json, 'availableUnits') ? undefined : (json['availableUnits'].map(_1.UnitFromJSON)),
        'bestStudyLink': !(0, runtime_1.exists)(json, 'bestStudyLink') ? undefined : json['bestStudyLink'],
        'bestStudyCard': !(0, runtime_1.exists)(json, 'bestStudyCard') ? undefined : (0, _1.CardFromJSON)(json['bestStudyCard']),
        'bestUserStudyLink': !(0, runtime_1.exists)(json, 'bestUserStudyLink') ? undefined : json['bestUserStudyLink'],
        'bestUserStudyCard': !(0, runtime_1.exists)(json, 'bestUserStudyCard') ? undefined : (0, _1.CardFromJSON)(json['bestUserStudyCard']),
        'bestPopulationStudyLink': !(0, runtime_1.exists)(json, 'bestPopulationStudyLink') ? undefined : json['bestPopulationStudyLink'],
        'bestPopulationStudyCard': !(0, runtime_1.exists)(json, 'bestPopulationStudyCard') ? undefined : (0, _1.CardFromJSON)(json['bestPopulationStudyCard']),
        'optimalValueMessage': !(0, runtime_1.exists)(json, 'optimalValueMessage') ? undefined : json['optimalValueMessage'],
        'commonOptimalValueMessage': !(0, runtime_1.exists)(json, 'commonOptimalValueMessage') ? undefined : json['commonOptimalValueMessage'],
        'userOptimalValueMessage': !(0, runtime_1.exists)(json, 'userOptimalValueMessage') ? undefined : json['userOptimalValueMessage'],
        'card': !(0, runtime_1.exists)(json, 'card') ? undefined : (0, _1.CardFromJSON)(json['card']),
        'clientId': !(0, runtime_1.exists)(json, 'clientId') ? undefined : json['clientId'],
        'combinationOperation': !(0, runtime_1.exists)(json, 'combinationOperation') ? undefined : json['combinationOperation'],
        'createdAt': !(0, runtime_1.exists)(json, 'createdAt') ? undefined : json['createdAt'],
        'displayName': !(0, runtime_1.exists)(json, 'displayName') ? undefined : json['displayName'],
        'unitAbbreviatedName': json['unitAbbreviatedName'],
        'unitCategoryId': !(0, runtime_1.exists)(json, 'unitCategoryId') ? undefined : json['unitCategoryId'],
        'unitCategoryName': !(0, runtime_1.exists)(json, 'unitCategoryName') ? undefined : json['unitCategoryName'],
        'unitId': !(0, runtime_1.exists)(json, 'unitId') ? undefined : json['unitId'],
        'unitName': !(0, runtime_1.exists)(json, 'unitName') ? undefined : json['unitName'],
        'defaultValue': !(0, runtime_1.exists)(json, 'defaultValue') ? undefined : json['defaultValue'],
        'enabled': !(0, runtime_1.exists)(json, 'enabled') ? undefined : json['enabled'],
        'email': !(0, runtime_1.exists)(json, 'email') ? undefined : json['email'],
        'errorMessage': !(0, runtime_1.exists)(json, 'errorMessage') ? undefined : json['errorMessage'],
        'fillingValue': !(0, runtime_1.exists)(json, 'fillingValue') ? undefined : json['fillingValue'],
        'firstDailyReminderTime': !(0, runtime_1.exists)(json, 'firstDailyReminderTime') ? undefined : json['firstDailyReminderTime'],
        'frequencyTextDescription': !(0, runtime_1.exists)(json, 'frequencyTextDescription') ? undefined : json['frequencyTextDescription'],
        'frequencyTextDescriptionWithTime': !(0, runtime_1.exists)(json, 'frequencyTextDescriptionWithTime') ? undefined : json['frequencyTextDescriptionWithTime'],
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'inputType': !(0, runtime_1.exists)(json, 'inputType') ? undefined : json['inputType'],
        'instructions': !(0, runtime_1.exists)(json, 'instructions') ? undefined : json['instructions'],
        'ionIcon': !(0, runtime_1.exists)(json, 'ionIcon') ? undefined : json['ionIcon'],
        'lastTracked': !(0, runtime_1.exists)(json, 'lastTracked') ? undefined : json['lastTracked'],
        'lastValue': !(0, runtime_1.exists)(json, 'lastValue') ? undefined : json['lastValue'],
        'latestTrackingReminderNotificationReminderTime': !(0, runtime_1.exists)(json, 'latestTrackingReminderNotificationReminderTime') ? undefined : json['latestTrackingReminderNotificationReminderTime'],
        'localDailyReminderNotificationTimes': !(0, runtime_1.exists)(json, 'localDailyReminderNotificationTimes') ? undefined : json['localDailyReminderNotificationTimes'],
        'localDailyReminderNotificationTimesForAllReminders': !(0, runtime_1.exists)(json, 'localDailyReminderNotificationTimesForAllReminders') ? undefined : json['localDailyReminderNotificationTimesForAllReminders'],
        'manualTracking': !(0, runtime_1.exists)(json, 'manualTracking') ? undefined : json['manualTracking'],
        'maximumAllowedValue': !(0, runtime_1.exists)(json, 'maximumAllowedValue') ? undefined : json['maximumAllowedValue'],
        'minimumAllowedValue': !(0, runtime_1.exists)(json, 'minimumAllowedValue') ? undefined : json['minimumAllowedValue'],
        'nextReminderTimeEpochSeconds': !(0, runtime_1.exists)(json, 'nextReminderTimeEpochSeconds') ? undefined : json['nextReminderTimeEpochSeconds'],
        'notificationBar': !(0, runtime_1.exists)(json, 'notificationBar') ? undefined : json['notificationBar'],
        'numberOfRawMeasurements': !(0, runtime_1.exists)(json, 'numberOfRawMeasurements') ? undefined : json['numberOfRawMeasurements'],
        'numberOfUniqueValues': !(0, runtime_1.exists)(json, 'numberOfUniqueValues') ? undefined : json['numberOfUniqueValues'],
        'outcome': !(0, runtime_1.exists)(json, 'outcome') ? undefined : json['outcome'],
        'pngPath': !(0, runtime_1.exists)(json, 'pngPath') ? undefined : json['pngPath'],
        'pngUrl': !(0, runtime_1.exists)(json, 'pngUrl') ? undefined : json['pngUrl'],
        'productUrl': !(0, runtime_1.exists)(json, 'productUrl') ? undefined : json['productUrl'],
        'popUp': !(0, runtime_1.exists)(json, 'popUp') ? undefined : json['popUp'],
        'question': !(0, runtime_1.exists)(json, 'question') ? undefined : json['question'],
        'longQuestion': !(0, runtime_1.exists)(json, 'longQuestion') ? undefined : json['longQuestion'],
        'reminderEndTime': !(0, runtime_1.exists)(json, 'reminderEndTime') ? undefined : json['reminderEndTime'],
        'reminderFrequency': json['reminderFrequency'],
        'reminderSound': !(0, runtime_1.exists)(json, 'reminderSound') ? undefined : json['reminderSound'],
        'reminderStartEpochSeconds': !(0, runtime_1.exists)(json, 'reminderStartEpochSeconds') ? undefined : json['reminderStartEpochSeconds'],
        'reminderStartTime': !(0, runtime_1.exists)(json, 'reminderStartTime') ? undefined : json['reminderStartTime'],
        'reminderStartTimeLocal': !(0, runtime_1.exists)(json, 'reminderStartTimeLocal') ? undefined : json['reminderStartTimeLocal'],
        'reminderStartTimeLocalHumanFormatted': !(0, runtime_1.exists)(json, 'reminderStartTimeLocalHumanFormatted') ? undefined : json['reminderStartTimeLocalHumanFormatted'],
        'repeating': !(0, runtime_1.exists)(json, 'repeating') ? undefined : json['repeating'],
        'secondDailyReminderTime': !(0, runtime_1.exists)(json, 'secondDailyReminderTime') ? undefined : json['secondDailyReminderTime'],
        'secondToLastValue': !(0, runtime_1.exists)(json, 'secondToLastValue') ? undefined : json['secondToLastValue'],
        'sms': !(0, runtime_1.exists)(json, 'sms') ? undefined : json['sms'],
        'startTrackingDate': !(0, runtime_1.exists)(json, 'startTrackingDate') ? undefined : json['startTrackingDate'],
        'stopTrackingDate': !(0, runtime_1.exists)(json, 'stopTrackingDate') ? undefined : json['stopTrackingDate'],
        'svgUrl': !(0, runtime_1.exists)(json, 'svgUrl') ? undefined : json['svgUrl'],
        'thirdDailyReminderTime': !(0, runtime_1.exists)(json, 'thirdDailyReminderTime') ? undefined : json['thirdDailyReminderTime'],
        'thirdToLastValue': !(0, runtime_1.exists)(json, 'thirdToLastValue') ? undefined : json['thirdToLastValue'],
        'trackingReminderId': !(0, runtime_1.exists)(json, 'trackingReminderId') ? undefined : json['trackingReminderId'],
        'trackingReminderImageUrl': !(0, runtime_1.exists)(json, 'trackingReminderImageUrl') ? undefined : json['trackingReminderImageUrl'],
        'upc': !(0, runtime_1.exists)(json, 'upc') ? undefined : json['upc'],
        'updatedAt': !(0, runtime_1.exists)(json, 'updatedAt') ? undefined : json['updatedAt'],
        'userId': !(0, runtime_1.exists)(json, 'userId') ? undefined : json['userId'],
        'userVariableUnitAbbreviatedName': !(0, runtime_1.exists)(json, 'userVariableUnitAbbreviatedName') ? undefined : json['userVariableUnitAbbreviatedName'],
        'userVariableUnitCategoryId': !(0, runtime_1.exists)(json, 'userVariableUnitCategoryId') ? undefined : json['userVariableUnitCategoryId'],
        'userVariableUnitCategoryName': !(0, runtime_1.exists)(json, 'userVariableUnitCategoryName') ? undefined : json['userVariableUnitCategoryName'],
        'userVariableUnitId': !(0, runtime_1.exists)(json, 'userVariableUnitId') ? undefined : json['userVariableUnitId'],
        'userVariableUnitName': !(0, runtime_1.exists)(json, 'userVariableUnitName') ? undefined : json['userVariableUnitName'],
        'userVariableVariableCategoryId': !(0, runtime_1.exists)(json, 'userVariableVariableCategoryId') ? undefined : json['userVariableVariableCategoryId'],
        'userVariableVariableCategoryName': !(0, runtime_1.exists)(json, 'userVariableVariableCategoryName') ? undefined : json['userVariableVariableCategoryName'],
        'valence': !(0, runtime_1.exists)(json, 'valence') ? undefined : json['valence'],
        'valueAndFrequencyTextDescription': !(0, runtime_1.exists)(json, 'valueAndFrequencyTextDescription') ? undefined : json['valueAndFrequencyTextDescription'],
        'valueAndFrequencyTextDescriptionWithTime': !(0, runtime_1.exists)(json, 'valueAndFrequencyTextDescriptionWithTime') ? undefined : json['valueAndFrequencyTextDescriptionWithTime'],
        'variableCategoryId': !(0, runtime_1.exists)(json, 'variableCategoryId') ? undefined : json['variableCategoryId'],
        'variableCategoryImageUrl': !(0, runtime_1.exists)(json, 'variableCategoryImageUrl') ? undefined : json['variableCategoryImageUrl'],
        'variableCategoryName': json['variableCategoryName'],
        'variableDescription': !(0, runtime_1.exists)(json, 'variableDescription') ? undefined : json['variableDescription'],
        'variableId': !(0, runtime_1.exists)(json, 'variableId') ? undefined : json['variableId'],
        'variableName': json['variableName'],
    };
}
exports.TrackingReminderFromJSONTyped = TrackingReminderFromJSONTyped;
function TrackingReminderToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'actionArray': value.actionArray === undefined ? undefined : (value.actionArray.map(_1.TrackingReminderNotificationActionToJSON)),
        'availableUnits': value.availableUnits === undefined ? undefined : (value.availableUnits.map(_1.UnitToJSON)),
        'bestStudyLink': value.bestStudyLink,
        'bestStudyCard': (0, _1.CardToJSON)(value.bestStudyCard),
        'bestUserStudyLink': value.bestUserStudyLink,
        'bestUserStudyCard': (0, _1.CardToJSON)(value.bestUserStudyCard),
        'bestPopulationStudyLink': value.bestPopulationStudyLink,
        'bestPopulationStudyCard': (0, _1.CardToJSON)(value.bestPopulationStudyCard),
        'optimalValueMessage': value.optimalValueMessage,
        'commonOptimalValueMessage': value.commonOptimalValueMessage,
        'userOptimalValueMessage': value.userOptimalValueMessage,
        'card': (0, _1.CardToJSON)(value.card),
        'clientId': value.clientId,
        'combinationOperation': value.combinationOperation,
        'createdAt': value.createdAt,
        'displayName': value.displayName,
        'unitAbbreviatedName': value.unitAbbreviatedName,
        'unitCategoryId': value.unitCategoryId,
        'unitCategoryName': value.unitCategoryName,
        'unitId': value.unitId,
        'unitName': value.unitName,
        'defaultValue': value.defaultValue,
        'enabled': value.enabled,
        'email': value.email,
        'errorMessage': value.errorMessage,
        'fillingValue': value.fillingValue,
        'firstDailyReminderTime': value.firstDailyReminderTime,
        'frequencyTextDescription': value.frequencyTextDescription,
        'frequencyTextDescriptionWithTime': value.frequencyTextDescriptionWithTime,
        'id': value.id,
        'inputType': value.inputType,
        'instructions': value.instructions,
        'ionIcon': value.ionIcon,
        'lastTracked': value.lastTracked,
        'lastValue': value.lastValue,
        'latestTrackingReminderNotificationReminderTime': value.latestTrackingReminderNotificationReminderTime,
        'localDailyReminderNotificationTimes': value.localDailyReminderNotificationTimes,
        'localDailyReminderNotificationTimesForAllReminders': value.localDailyReminderNotificationTimesForAllReminders,
        'manualTracking': value.manualTracking,
        'maximumAllowedValue': value.maximumAllowedValue,
        'minimumAllowedValue': value.minimumAllowedValue,
        'nextReminderTimeEpochSeconds': value.nextReminderTimeEpochSeconds,
        'notificationBar': value.notificationBar,
        'numberOfRawMeasurements': value.numberOfRawMeasurements,
        'numberOfUniqueValues': value.numberOfUniqueValues,
        'outcome': value.outcome,
        'pngPath': value.pngPath,
        'pngUrl': value.pngUrl,
        'productUrl': value.productUrl,
        'popUp': value.popUp,
        'question': value.question,
        'longQuestion': value.longQuestion,
        'reminderEndTime': value.reminderEndTime,
        'reminderFrequency': value.reminderFrequency,
        'reminderSound': value.reminderSound,
        'reminderStartEpochSeconds': value.reminderStartEpochSeconds,
        'reminderStartTime': value.reminderStartTime,
        'reminderStartTimeLocal': value.reminderStartTimeLocal,
        'reminderStartTimeLocalHumanFormatted': value.reminderStartTimeLocalHumanFormatted,
        'repeating': value.repeating,
        'secondDailyReminderTime': value.secondDailyReminderTime,
        'secondToLastValue': value.secondToLastValue,
        'sms': value.sms,
        'startTrackingDate': value.startTrackingDate,
        'stopTrackingDate': value.stopTrackingDate,
        'svgUrl': value.svgUrl,
        'thirdDailyReminderTime': value.thirdDailyReminderTime,
        'thirdToLastValue': value.thirdToLastValue,
        'trackingReminderId': value.trackingReminderId,
        'trackingReminderImageUrl': value.trackingReminderImageUrl,
        'upc': value.upc,
        'updatedAt': value.updatedAt,
        'userId': value.userId,
        'userVariableUnitAbbreviatedName': value.userVariableUnitAbbreviatedName,
        'userVariableUnitCategoryId': value.userVariableUnitCategoryId,
        'userVariableUnitCategoryName': value.userVariableUnitCategoryName,
        'userVariableUnitId': value.userVariableUnitId,
        'userVariableUnitName': value.userVariableUnitName,
        'userVariableVariableCategoryId': value.userVariableVariableCategoryId,
        'userVariableVariableCategoryName': value.userVariableVariableCategoryName,
        'valence': value.valence,
        'valueAndFrequencyTextDescription': value.valueAndFrequencyTextDescription,
        'valueAndFrequencyTextDescriptionWithTime': value.valueAndFrequencyTextDescriptionWithTime,
        'variableCategoryId': value.variableCategoryId,
        'variableCategoryImageUrl': value.variableCategoryImageUrl,
        'variableCategoryName': value.variableCategoryName,
        'variableDescription': value.variableDescription,
        'variableId': value.variableId,
        'variableName': value.variableName,
    };
}
exports.TrackingReminderToJSON = TrackingReminderToJSON;
//# sourceMappingURL=TrackingReminder.js.map
