"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrackingReminderNotificationPostToJSON = exports.TrackingReminderNotificationPostFromJSONTyped = exports.TrackingReminderNotificationPostFromJSON = exports.TrackingReminderNotificationPostActionEnum = void 0;
var runtime_1 = require("../runtime");
/**
* @export
* @enum {string}
*/
var TrackingReminderNotificationPostActionEnum;
(function (TrackingReminderNotificationPostActionEnum) {
    TrackingReminderNotificationPostActionEnum["Skip"] = "skip";
    TrackingReminderNotificationPostActionEnum["Snooze"] = "snooze";
    TrackingReminderNotificationPostActionEnum["Track"] = "track";
})(TrackingReminderNotificationPostActionEnum = exports.TrackingReminderNotificationPostActionEnum || (exports.TrackingReminderNotificationPostActionEnum = {}));
function TrackingReminderNotificationPostFromJSON(json) {
    return TrackingReminderNotificationPostFromJSONTyped(json, false);
}
exports.TrackingReminderNotificationPostFromJSON = TrackingReminderNotificationPostFromJSON;
function TrackingReminderNotificationPostFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'action': json['action'],
        'id': json['id'],
        'modifiedValue': !(0, runtime_1.exists)(json, 'modifiedValue') ? undefined : json['modifiedValue'],
    };
}
exports.TrackingReminderNotificationPostFromJSONTyped = TrackingReminderNotificationPostFromJSONTyped;
function TrackingReminderNotificationPostToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'action': value.action,
        'id': value.id,
        'modifiedValue': value.modifiedValue,
    };
}
exports.TrackingReminderNotificationPostToJSON = TrackingReminderNotificationPostToJSON;
//# sourceMappingURL=TrackingReminderNotificationPost.js.map