"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrackingReminderNotificationActionToJSON = exports.TrackingReminderNotificationActionFromJSONTyped = exports.TrackingReminderNotificationActionFromJSON = void 0;
var runtime_1 = require("../runtime");
function TrackingReminderNotificationActionFromJSON(json) {
    return TrackingReminderNotificationActionFromJSONTyped(json, false);
}
exports.TrackingReminderNotificationActionFromJSON = TrackingReminderNotificationActionFromJSON;
function TrackingReminderNotificationActionFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'action': json['action'],
        'callback': json['callback'],
        'modifiedValue': json['modifiedValue'],
        'title': json['title'],
        'longTitle': !(0, runtime_1.exists)(json, 'longTitle') ? undefined : json['longTitle'],
        'shortTitle': !(0, runtime_1.exists)(json, 'shortTitle') ? undefined : json['shortTitle'],
    };
}
exports.TrackingReminderNotificationActionFromJSONTyped = TrackingReminderNotificationActionFromJSONTyped;
function TrackingReminderNotificationActionToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'action': value.action,
        'callback': value.callback,
        'modifiedValue': value.modifiedValue,
        'title': value.title,
        'longTitle': value.longTitle,
        'shortTitle': value.shortTitle,
    };
}
exports.TrackingReminderNotificationActionToJSON = TrackingReminderNotificationActionToJSON;
//# sourceMappingURL=TrackingReminderNotificationAction.js.map