"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrackingReminderNotificationTrackAllActionToJSON = exports.TrackingReminderNotificationTrackAllActionFromJSONTyped = exports.TrackingReminderNotificationTrackAllActionFromJSON = void 0;
function TrackingReminderNotificationTrackAllActionFromJSON(json) {
    return TrackingReminderNotificationTrackAllActionFromJSONTyped(json, false);
}
exports.TrackingReminderNotificationTrackAllActionFromJSON = TrackingReminderNotificationTrackAllActionFromJSON;
function TrackingReminderNotificationTrackAllActionFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'action': json['action'],
        'callback': json['callback'],
        'modifiedValue': json['modifiedValue'],
        'title': json['title'],
    };
}
exports.TrackingReminderNotificationTrackAllActionFromJSONTyped = TrackingReminderNotificationTrackAllActionFromJSONTyped;
function TrackingReminderNotificationTrackAllActionToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'action': value.action,
        'callback': value.callback,
        'modifiedValue': value.modifiedValue,
        'title': value.title,
    };
}
exports.TrackingReminderNotificationTrackAllActionToJSON = TrackingReminderNotificationTrackAllActionToJSON;
//# sourceMappingURL=TrackingReminderNotificationTrackAllAction.js.map