"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A platform for participant-centered research and personal data exploration
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrackingReminderNotificationToJSON = exports.TrackingReminderNotificationFromJSONTyped = exports.TrackingReminderNotificationFromJSON = exports.TrackingReminderNotificationVariableCategoryNameEnum = exports.TrackingReminderNotificationCombinationOperationEnum = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
/**
* @export
* @enum {string}
*/
var TrackingReminderNotificationCombinationOperationEnum;
(function (TrackingReminderNotificationCombinationOperationEnum) {
    TrackingReminderNotificationCombinationOperationEnum["Mean"] = "MEAN";
    TrackingReminderNotificationCombinationOperationEnum["Sum"] = "SUM";
})(TrackingReminderNotificationCombinationOperationEnum = exports.TrackingReminderNotificationCombinationOperationEnum || (exports.TrackingReminderNotificationCombinationOperationEnum = {})); /**
* @export
* @enum {string}
*/
var TrackingReminderNotificationVariableCategoryNameEnum;
(function (TrackingReminderNotificationVariableCategoryNameEnum) {
    TrackingReminderNotificationVariableCategoryNameEnum["Activity"] = "Activity";
    TrackingReminderNotificationVariableCategoryNameEnum["Books"] = "Books";
    TrackingReminderNotificationVariableCategoryNameEnum["CausesOfIllness"] = "Causes of Illness";
    TrackingReminderNotificationVariableCategoryNameEnum["CognitivePerformance"] = "Cognitive Performance";
    TrackingReminderNotificationVariableCategoryNameEnum["Conditions"] = "Conditions";
    TrackingReminderNotificationVariableCategoryNameEnum["Emotions"] = "Emotions";
    TrackingReminderNotificationVariableCategoryNameEnum["Environment"] = "Environment";
    TrackingReminderNotificationVariableCategoryNameEnum["Foods"] = "Foods";
    TrackingReminderNotificationVariableCategoryNameEnum["Goals"] = "Goals";
    TrackingReminderNotificationVariableCategoryNameEnum["Locations"] = "Locations";
    TrackingReminderNotificationVariableCategoryNameEnum["Miscellaneous"] = "Miscellaneous";
    TrackingReminderNotificationVariableCategoryNameEnum["MoviesAndTv"] = "Movies and TV";
    TrackingReminderNotificationVariableCategoryNameEnum["Music"] = "Music";
    TrackingReminderNotificationVariableCategoryNameEnum["Nutrients"] = "Nutrients";
    TrackingReminderNotificationVariableCategoryNameEnum["Payments"] = "Payments";
    TrackingReminderNotificationVariableCategoryNameEnum["PhysicalActivities"] = "Physical Activities";
    TrackingReminderNotificationVariableCategoryNameEnum["Physique"] = "Physique";
    TrackingReminderNotificationVariableCategoryNameEnum["Sleep"] = "Sleep";
    TrackingReminderNotificationVariableCategoryNameEnum["SocialInteractions"] = "Social Interactions";
    TrackingReminderNotificationVariableCategoryNameEnum["Software"] = "Software";
    TrackingReminderNotificationVariableCategoryNameEnum["Symptoms"] = "Symptoms";
    TrackingReminderNotificationVariableCategoryNameEnum["Treatments"] = "Treatments";
    TrackingReminderNotificationVariableCategoryNameEnum["VitalSigns"] = "Vital Signs";
})(TrackingReminderNotificationVariableCategoryNameEnum = exports.TrackingReminderNotificationVariableCategoryNameEnum || (exports.TrackingReminderNotificationVariableCategoryNameEnum = {}));
function TrackingReminderNotificationFromJSON(json) {
    return TrackingReminderNotificationFromJSONTyped(json, false);
}
exports.TrackingReminderNotificationFromJSON = TrackingReminderNotificationFromJSON;
function TrackingReminderNotificationFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'actionArray': (json['actionArray'].map(_1.TrackingReminderNotificationActionFromJSON)),
        'availableUnits': (json['availableUnits'].map(_1.UnitFromJSON)),
        'bestStudyLink': !(0, runtime_1.exists)(json, 'bestStudyLink') ? undefined : json['bestStudyLink'],
        'bestStudyCard': !(0, runtime_1.exists)(json, 'bestStudyCard') ? undefined : (0, _1.CardFromJSON)(json['bestStudyCard']),
        'bestUserStudyLink': !(0, runtime_1.exists)(json, 'bestUserStudyLink') ? undefined : json['bestUserStudyLink'],
        'bestUserStudyCard': !(0, runtime_1.exists)(json, 'bestUserStudyCard') ? undefined : (0, _1.CardFromJSON)(json['bestUserStudyCard']),
        'bestPopulationStudyLink': !(0, runtime_1.exists)(json, 'bestPopulationStudyLink') ? undefined : json['bestPopulationStudyLink'],
        'bestPopulationStudyCard': !(0, runtime_1.exists)(json, 'bestPopulationStudyCard') ? undefined : (0, _1.CardFromJSON)(json['bestPopulationStudyCard']),
        'optimalValueMessage': !(0, runtime_1.exists)(json, 'optimalValueMessage') ? undefined : json['optimalValueMessage'],
        'commonOptimalValueMessage': !(0, runtime_1.exists)(json, 'commonOptimalValueMessage') ? undefined : json['commonOptimalValueMessage'],
        'userOptimalValueMessage': !(0, runtime_1.exists)(json, 'userOptimalValueMessage') ? undefined : json['userOptimalValueMessage'],
        'card': !(0, runtime_1.exists)(json, 'card') ? undefined : (0, _1.CardFromJSON)(json['card']),
        'clientId': !(0, runtime_1.exists)(json, 'clientId') ? undefined : json['clientId'],
        'combinationOperation': !(0, runtime_1.exists)(json, 'combinationOperation') ? undefined : json['combinationOperation'],
        'createdAt': !(0, runtime_1.exists)(json, 'createdAt') ? undefined : json['createdAt'],
        'displayName': !(0, runtime_1.exists)(json, 'displayName') ? undefined : json['displayName'],
        'modifiedValue': !(0, runtime_1.exists)(json, 'modifiedValue') ? undefined : json['modifiedValue'],
        'unitAbbreviatedName': !(0, runtime_1.exists)(json, 'unitAbbreviatedName') ? undefined : json['unitAbbreviatedName'],
        'unitCategoryId': !(0, runtime_1.exists)(json, 'unitCategoryId') ? undefined : json['unitCategoryId'],
        'unitCategoryName': !(0, runtime_1.exists)(json, 'unitCategoryName') ? undefined : json['unitCategoryName'],
        'unitId': !(0, runtime_1.exists)(json, 'unitId') ? undefined : json['unitId'],
        'unitName': !(0, runtime_1.exists)(json, 'unitName') ? undefined : json['unitName'],
        'defaultValue': !(0, runtime_1.exists)(json, 'defaultValue') ? undefined : json['defaultValue'],
        'description': !(0, runtime_1.exists)(json, 'description') ? undefined : json['description'],
        'email': !(0, runtime_1.exists)(json, 'email') ? undefined : json['email'],
        'fillingValue': json['fillingValue'],
        'iconIcon': !(0, runtime_1.exists)(json, 'iconIcon') ? undefined : json['iconIcon'],
        'id': json['id'],
        'imageUrl': !(0, runtime_1.exists)(json, 'imageUrl') ? undefined : json['imageUrl'],
        'inputType': !(0, runtime_1.exists)(json, 'inputType') ? undefined : json['inputType'],
        'ionIcon': !(0, runtime_1.exists)(json, 'ionIcon') ? undefined : json['ionIcon'],
        'lastValue': !(0, runtime_1.exists)(json, 'lastValue') ? undefined : json['lastValue'],
        'manualTracking': !(0, runtime_1.exists)(json, 'manualTracking') ? undefined : json['manualTracking'],
        'maximumAllowedValue': !(0, runtime_1.exists)(json, 'maximumAllowedValue') ? undefined : json['maximumAllowedValue'],
        'minimumAllowedValue': !(0, runtime_1.exists)(json, 'minimumAllowedValue') ? undefined : json['minimumAllowedValue'],
        'mostCommonValue': !(0, runtime_1.exists)(json, 'mostCommonValue') ? undefined : json['mostCommonValue'],
        'notificationBar': !(0, runtime_1.exists)(json, 'notificationBar') ? undefined : json['notificationBar'],
        'notifiedAt': !(0, runtime_1.exists)(json, 'notifiedAt') ? undefined : json['notifiedAt'],
        'numberOfUniqueValues': !(0, runtime_1.exists)(json, 'numberOfUniqueValues') ? undefined : json['numberOfUniqueValues'],
        'outcome': !(0, runtime_1.exists)(json, 'outcome') ? undefined : json['outcome'],
        'pngPath': !(0, runtime_1.exists)(json, 'pngPath') ? undefined : json['pngPath'],
        'pngUrl': !(0, runtime_1.exists)(json, 'pngUrl') ? undefined : json['pngUrl'],
        'popUp': !(0, runtime_1.exists)(json, 'popUp') ? undefined : json['popUp'],
        'productUrl': !(0, runtime_1.exists)(json, 'productUrl') ? undefined : json['productUrl'],
        'question': !(0, runtime_1.exists)(json, 'question') ? undefined : json['question'],
        'longQuestion': !(0, runtime_1.exists)(json, 'longQuestion') ? undefined : json['longQuestion'],
        'reminderEndTime': !(0, runtime_1.exists)(json, 'reminderEndTime') ? undefined : json['reminderEndTime'],
        'reminderFrequency': !(0, runtime_1.exists)(json, 'reminderFrequency') ? undefined : json['reminderFrequency'],
        'reminderSound': !(0, runtime_1.exists)(json, 'reminderSound') ? undefined : json['reminderSound'],
        'reminderStartTime': !(0, runtime_1.exists)(json, 'reminderStartTime') ? undefined : json['reminderStartTime'],
        'reminderTime': !(0, runtime_1.exists)(json, 'reminderTime') ? undefined : json['reminderTime'],
        'secondMostCommonValue': !(0, runtime_1.exists)(json, 'secondMostCommonValue') ? undefined : json['secondMostCommonValue'],
        'secondToLastValue': !(0, runtime_1.exists)(json, 'secondToLastValue') ? undefined : json['secondToLastValue'],
        'sms': !(0, runtime_1.exists)(json, 'sms') ? undefined : json['sms'],
        'svgUrl': !(0, runtime_1.exists)(json, 'svgUrl') ? undefined : json['svgUrl'],
        'thirdMostCommonValue': !(0, runtime_1.exists)(json, 'thirdMostCommonValue') ? undefined : json['thirdMostCommonValue'],
        'thirdToLastValue': !(0, runtime_1.exists)(json, 'thirdToLastValue') ? undefined : json['thirdToLastValue'],
        'title': !(0, runtime_1.exists)(json, 'title') ? undefined : json['title'],
        'total': !(0, runtime_1.exists)(json, 'total') ? undefined : json['total'],
        'trackAllActions': (json['trackAllActions'].map(_1.TrackingReminderNotificationTrackAllActionFromJSON)),
        'trackingReminderId': !(0, runtime_1.exists)(json, 'trackingReminderId') ? undefined : json['trackingReminderId'],
        'trackingReminderImageUrl': !(0, runtime_1.exists)(json, 'trackingReminderImageUrl') ? undefined : json['trackingReminderImageUrl'],
        'trackingReminderNotificationId': !(0, runtime_1.exists)(json, 'trackingReminderNotificationId') ? undefined : json['trackingReminderNotificationId'],
        'trackingReminderNotificationTime': !(0, runtime_1.exists)(json, 'trackingReminderNotificationTime') ? undefined : json['trackingReminderNotificationTime'],
        'trackingReminderNotificationTimeEpoch': !(0, runtime_1.exists)(json, 'trackingReminderNotificationTimeEpoch') ? undefined : json['trackingReminderNotificationTimeEpoch'],
        'trackingReminderNotificationTimeLocal': !(0, runtime_1.exists)(json, 'trackingReminderNotificationTimeLocal') ? undefined : json['trackingReminderNotificationTimeLocal'],
        'trackingReminderNotificationTimeLocalHumanString': !(0, runtime_1.exists)(json, 'trackingReminderNotificationTimeLocalHumanString') ? undefined : json['trackingReminderNotificationTimeLocalHumanString'],
        'updatedAt': !(0, runtime_1.exists)(json, 'updatedAt') ? undefined : json['updatedAt'],
        'userId': !(0, runtime_1.exists)(json, 'userId') ? undefined : json['userId'],
        'userVariableUnitAbbreviatedName': !(0, runtime_1.exists)(json, 'userVariableUnitAbbreviatedName') ? undefined : json['userVariableUnitAbbreviatedName'],
        'userVariableUnitCategoryId': !(0, runtime_1.exists)(json, 'userVariableUnitCategoryId') ? undefined : json['userVariableUnitCategoryId'],
        'userVariableUnitCategoryName': !(0, runtime_1.exists)(json, 'userVariableUnitCategoryName') ? undefined : json['userVariableUnitCategoryName'],
        'userVariableUnitId': !(0, runtime_1.exists)(json, 'userVariableUnitId') ? undefined : json['userVariableUnitId'],
        'userVariableUnitName': !(0, runtime_1.exists)(json, 'userVariableUnitName') ? undefined : json['userVariableUnitName'],
        'userVariableVariableCategoryId': !(0, runtime_1.exists)(json, 'userVariableVariableCategoryId') ? undefined : json['userVariableVariableCategoryId'],
        'userVariableVariableCategoryName': !(0, runtime_1.exists)(json, 'userVariableVariableCategoryName') ? undefined : json['userVariableVariableCategoryName'],
        'valence': !(0, runtime_1.exists)(json, 'valence') ? undefined : json['valence'],
        'variableCategoryId': !(0, runtime_1.exists)(json, 'variableCategoryId') ? undefined : json['variableCategoryId'],
        'variableCategoryImageUrl': !(0, runtime_1.exists)(json, 'variableCategoryImageUrl') ? undefined : json['variableCategoryImageUrl'],
        'variableCategoryName': !(0, runtime_1.exists)(json, 'variableCategoryName') ? undefined : json['variableCategoryName'],
        'variableId': !(0, runtime_1.exists)(json, 'variableId') ? undefined : json['variableId'],
        'variableImageUrl': !(0, runtime_1.exists)(json, 'variableImageUrl') ? undefined : json['variableImageUrl'],
        'variableName': !(0, runtime_1.exists)(json, 'variableName') ? undefined : json['variableName'],
    };
}
exports.TrackingReminderNotificationFromJSONTyped = TrackingReminderNotificationFromJSONTyped;
function TrackingReminderNotificationToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'actionArray': (value.actionArray.map(_1.TrackingReminderNotificationActionToJSON)),
        'availableUnits': (value.availableUnits.map(_1.UnitToJSON)),
        'bestStudyLink': value.bestStudyLink,
        'bestStudyCard': (0, _1.CardToJSON)(value.bestStudyCard),
        'bestUserStudyLink': value.bestUserStudyLink,
        'bestUserStudyCard': (0, _1.CardToJSON)(value.bestUserStudyCard),
        'bestPopulationStudyLink': value.bestPopulationStudyLink,
        'bestPopulationStudyCard': (0, _1.CardToJSON)(value.bestPopulationStudyCard),
        'optimalValueMessage': value.optimalValueMessage,
        'commonOptimalValueMessage': value.commonOptimalValueMessage,
        'userOptimalValueMessage': value.userOptimalValueMessage,
        'card': (0, _1.CardToJSON)(value.card),
        'clientId': value.clientId,
        'combinationOperation': value.combinationOperation,
        'createdAt': value.createdAt,
        'displayName': value.displayName,
        'modifiedValue': value.modifiedValue,
        'unitAbbreviatedName': value.unitAbbreviatedName,
        'unitCategoryId': value.unitCategoryId,
        'unitCategoryName': value.unitCategoryName,
        'unitId': value.unitId,
        'unitName': value.unitName,
        'defaultValue': value.defaultValue,
        'description': value.description,
        'email': value.email,
        'fillingValue': value.fillingValue,
        'iconIcon': value.iconIcon,
        'id': value.id,
        'imageUrl': value.imageUrl,
        'inputType': value.inputType,
        'ionIcon': value.ionIcon,
        'lastValue': value.lastValue,
        'manualTracking': value.manualTracking,
        'maximumAllowedValue': value.maximumAllowedValue,
        'minimumAllowedValue': value.minimumAllowedValue,
        'mostCommonValue': value.mostCommonValue,
        'notificationBar': value.notificationBar,
        'notifiedAt': value.notifiedAt,
        'numberOfUniqueValues': value.numberOfUniqueValues,
        'outcome': value.outcome,
        'pngPath': value.pngPath,
        'pngUrl': value.pngUrl,
        'popUp': value.popUp,
        'productUrl': value.productUrl,
        'question': value.question,
        'longQuestion': value.longQuestion,
        'reminderEndTime': value.reminderEndTime,
        'reminderFrequency': value.reminderFrequency,
        'reminderSound': value.reminderSound,
        'reminderStartTime': value.reminderStartTime,
        'reminderTime': value.reminderTime,
        'secondMostCommonValue': value.secondMostCommonValue,
        'secondToLastValue': value.secondToLastValue,
        'sms': value.sms,
        'svgUrl': value.svgUrl,
        'thirdMostCommonValue': value.thirdMostCommonValue,
        'thirdToLastValue': value.thirdToLastValue,
        'title': value.title,
        'total': value.total,
        'trackAllActions': (value.trackAllActions.map(_1.TrackingReminderNotificationTrackAllActionToJSON)),
        'trackingReminderId': value.trackingReminderId,
        'trackingReminderImageUrl': value.trackingReminderImageUrl,
        'trackingReminderNotificationId': value.trackingReminderNotificationId,
        'trackingReminderNotificationTime': value.trackingReminderNotificationTime,
        'trackingReminderNotificationTimeEpoch': value.trackingReminderNotificationTimeEpoch,
        'trackingReminderNotificationTimeLocal': value.trackingReminderNotificationTimeLocal,
        'trackingReminderNotificationTimeLocalHumanString': value.trackingReminderNotificationTimeLocalHumanString,
        'updatedAt': value.updatedAt,
        'userId': value.userId,
        'userVariableUnitAbbreviatedName': value.userVariableUnitAbbreviatedName,
        'userVariableUnitCategoryId': value.userVariableUnitCategoryId,
        'userVariableUnitCategoryName': value.userVariableUnitCategoryName,
        'userVariableUnitId': value.userVariableUnitId,
        'userVariableUnitName': value.userVariableUnitName,
        'userVariableVariableCategoryId': value.userVariableVariableCategoryId,
        'userVariableVariableCategoryName': value.userVariableVariableCategoryName,
        'valence': value.valence,
        'variableCategoryId': value.variableCategoryId,
        'variableCategoryImageUrl': value.variableCategoryImageUrl,
        'variableCategoryName': value.variableCategoryName,
        'variableId': value.variableId,
        'variableImageUrl': value.variableImageUrl,
        'variableName': value.variableName,
    };
}
exports.TrackingReminderNotificationToJSON = TrackingReminderNotificationToJSON;
//# sourceMappingURL=TrackingReminderNotification.js.map