"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserTagToJSON = exports.UserTagFromJSONTyped = exports.UserTagFromJSON = void 0;
function UserTagFromJSON(json) {
    return UserTagFromJSONTyped(json, false);
}
exports.UserTagFromJSON = UserTagFromJSON;
function UserTagFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'conversionFactor': json['conversionFactor'],
        'taggedVariableId': json['taggedVariableId'],
        'tagVariableId': json['tagVariableId'],
    };
}
exports.UserTagFromJSONTyped = UserTagFromJSONTyped;
function UserTagToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'conversionFactor': value.conversionFactor,
        'taggedVariableId': value.taggedVariableId,
        'tagVariableId': value.tagVariableId,
    };
}
exports.UserTagToJSON = UserTagToJSON;
//# sourceMappingURL=UserTag.js.map
