/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserVariableDelete
 */
export interface UserVariableDelete {
    /**
     * Id of the variable whose measurements should be deleted
     * @type {number}
     * @memberof UserVariableDelete
     */
    variableId: number;
}

export function UserVariableDeleteFromJSON(json: any): UserVariableDelete {
    return UserVariableDeleteFromJSONTyped(json, false);
}

export function UserVariableDeleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserVariableDelete {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'variableId': json['variableId'],
    };
}

export function UserVariableDeleteToJSON(value?: UserVariableDelete | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'variableId': value.variableId,
    };
}


