"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VariableCategoryToJSON = exports.VariableCategoryFromJSONTyped = exports.VariableCategoryFromJSON = exports.VariableCategoryVariableCategoryNameEnum = void 0;
var runtime_1 = require("../runtime");
/**
* @export
* @enum {string}
*/
var VariableCategoryVariableCategoryNameEnum;
(function (VariableCategoryVariableCategoryNameEnum) {
    VariableCategoryVariableCategoryNameEnum["Activity"] = "Activity";
    VariableCategoryVariableCategoryNameEnum["Books"] = "Books";
    VariableCategoryVariableCategoryNameEnum["CausesOfIllness"] = "Causes of Illness";
    VariableCategoryVariableCategoryNameEnum["CognitivePerformance"] = "Cognitive Performance";
    VariableCategoryVariableCategoryNameEnum["Conditions"] = "Conditions";
    VariableCategoryVariableCategoryNameEnum["Emotions"] = "Emotions";
    VariableCategoryVariableCategoryNameEnum["Environment"] = "Environment";
    VariableCategoryVariableCategoryNameEnum["Foods"] = "Foods";
    VariableCategoryVariableCategoryNameEnum["Goals"] = "Goals";
    VariableCategoryVariableCategoryNameEnum["Locations"] = "Locations";
    VariableCategoryVariableCategoryNameEnum["Miscellaneous"] = "Miscellaneous";
    VariableCategoryVariableCategoryNameEnum["MoviesAndTv"] = "Movies and TV";
    VariableCategoryVariableCategoryNameEnum["Music"] = "Music";
    VariableCategoryVariableCategoryNameEnum["Nutrients"] = "Nutrients";
    VariableCategoryVariableCategoryNameEnum["Payments"] = "Payments";
    VariableCategoryVariableCategoryNameEnum["PhysicalActivities"] = "Physical Activities";
    VariableCategoryVariableCategoryNameEnum["Physique"] = "Physique";
    VariableCategoryVariableCategoryNameEnum["Sleep"] = "Sleep";
    VariableCategoryVariableCategoryNameEnum["SocialInteractions"] = "Social Interactions";
    VariableCategoryVariableCategoryNameEnum["Software"] = "Software";
    VariableCategoryVariableCategoryNameEnum["Symptoms"] = "Symptoms";
    VariableCategoryVariableCategoryNameEnum["Treatments"] = "Treatments";
    VariableCategoryVariableCategoryNameEnum["VitalSigns"] = "Vital Signs";
})(VariableCategoryVariableCategoryNameEnum = exports.VariableCategoryVariableCategoryNameEnum || (exports.VariableCategoryVariableCategoryNameEnum = {}));
function VariableCategoryFromJSON(json) {
    return VariableCategoryFromJSONTyped(json, false);
}
exports.VariableCategoryFromJSON = VariableCategoryFromJSON;
function VariableCategoryFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'appType': !(0, runtime_1.exists)(json, 'appType') ? undefined : json['appType'],
        'causeOnly': !(0, runtime_1.exists)(json, 'causeOnly') ? undefined : json['causeOnly'],
        'combinationOperation': !(0, runtime_1.exists)(json, 'combinationOperation') ? undefined : json['combinationOperation'],
        'createdTime': !(0, runtime_1.exists)(json, 'createdTime') ? undefined : json['createdTime'],
        'unitAbbreviatedName': !(0, runtime_1.exists)(json, 'unitAbbreviatedName') ? undefined : json['unitAbbreviatedName'],
        'unitId': !(0, runtime_1.exists)(json, 'unitId') ? undefined : json['unitId'],
        'durationOfAction': !(0, runtime_1.exists)(json, 'durationOfAction') ? undefined : json['durationOfAction'],
        'fillingValue': !(0, runtime_1.exists)(json, 'fillingValue') ? undefined : json['fillingValue'],
        'helpText': !(0, runtime_1.exists)(json, 'helpText') ? undefined : json['helpText'],
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'imageUrl': !(0, runtime_1.exists)(json, 'imageUrl') ? undefined : json['imageUrl'],
        'ionIcon': !(0, runtime_1.exists)(json, 'ionIcon') ? undefined : json['ionIcon'],
        'manualTracking': !(0, runtime_1.exists)(json, 'manualTracking') ? undefined : json['manualTracking'],
        'maximumAllowedValue': !(0, runtime_1.exists)(json, 'maximumAllowedValue') ? undefined : json['maximumAllowedValue'],
        'measurementSynonymSingularLowercase': !(0, runtime_1.exists)(json, 'measurementSynonymSingularLowercase') ? undefined : json['measurementSynonymSingularLowercase'],
        'minimumAllowedValue': !(0, runtime_1.exists)(json, 'minimumAllowedValue') ? undefined : json['minimumAllowedValue'],
        'moreInfo': !(0, runtime_1.exists)(json, 'moreInfo') ? undefined : json['moreInfo'],
        'name': json['name'],
        'onsetDelay': !(0, runtime_1.exists)(json, 'onsetDelay') ? undefined : json['onsetDelay'],
        'outcome': !(0, runtime_1.exists)(json, 'outcome') ? undefined : json['outcome'],
        'pngPath': !(0, runtime_1.exists)(json, 'pngPath') ? undefined : json['pngPath'],
        'pngUrl': !(0, runtime_1.exists)(json, 'pngUrl') ? undefined : json['pngUrl'],
        '_public': !(0, runtime_1.exists)(json, 'public') ? undefined : json['public'],
        'svgPath': !(0, runtime_1.exists)(json, 'svgPath') ? undefined : json['svgPath'],
        'svgUrl': !(0, runtime_1.exists)(json, 'svgUrl') ? undefined : json['svgUrl'],
        'updated': !(0, runtime_1.exists)(json, 'updated') ? undefined : json['updated'],
        'updatedTime': !(0, runtime_1.exists)(json, 'updatedTime') ? undefined : json['updatedTime'],
        'variableCategoryName': !(0, runtime_1.exists)(json, 'variableCategoryName') ? undefined : json['variableCategoryName'],
        'variableCategoryNameSingular': !(0, runtime_1.exists)(json, 'variableCategoryNameSingular') ? undefined : json['variableCategoryNameSingular'],
    };
}
exports.VariableCategoryFromJSONTyped = VariableCategoryFromJSONTyped;
function VariableCategoryToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'appType': value.appType,
        'causeOnly': value.causeOnly,
        'combinationOperation': value.combinationOperation,
        'createdTime': value.createdTime,
        'unitAbbreviatedName': value.unitAbbreviatedName,
        'unitId': value.unitId,
        'durationOfAction': value.durationOfAction,
        'fillingValue': value.fillingValue,
        'helpText': value.helpText,
        'id': value.id,
        'imageUrl': value.imageUrl,
        'ionIcon': value.ionIcon,
        'manualTracking': value.manualTracking,
        'maximumAllowedValue': value.maximumAllowedValue,
        'measurementSynonymSingularLowercase': value.measurementSynonymSingularLowercase,
        'minimumAllowedValue': value.minimumAllowedValue,
        'moreInfo': value.moreInfo,
        'name': value.name,
        'onsetDelay': value.onsetDelay,
        'outcome': value.outcome,
        'pngPath': value.pngPath,
        'pngUrl': value.pngUrl,
        'public': value._public,
        'svgPath': value.svgPath,
        'svgUrl': value.svgUrl,
        'updated': value.updated,
        'updatedTime': value.updatedTime,
        'variableCategoryName': value.variableCategoryName,
        'variableCategoryNameSingular': value.variableCategoryNameSingular,
    };
}
exports.VariableCategoryToJSON = VariableCategoryToJSON;
//# sourceMappingURL=VariableCategory.js.map
