"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VariableToJSON = exports.VariableFromJSONTyped = exports.VariableFromJSON = exports.VariableVariableCategoryNameEnum = exports.VariableFillingTypeEnum = exports.VariableCombinationOperationEnum = void 0;
var runtime_1 = require("../runtime");
var _1 = require("./");
/**
* @export
* @enum {string}
*/
var VariableCombinationOperationEnum;
(function (VariableCombinationOperationEnum) {
    VariableCombinationOperationEnum["Mean"] = "MEAN";
    VariableCombinationOperationEnum["Sum"] = "SUM";
})(VariableCombinationOperationEnum = exports.VariableCombinationOperationEnum || (exports.VariableCombinationOperationEnum = {})); /**
* @export
* @enum {string}
*/
var VariableFillingTypeEnum;
(function (VariableFillingTypeEnum) {
    VariableFillingTypeEnum["None"] = "none";
    VariableFillingTypeEnum["ZeroFilling"] = "zero-filling";
    VariableFillingTypeEnum["ValueFilling"] = "value-filling";
})(VariableFillingTypeEnum = exports.VariableFillingTypeEnum || (exports.VariableFillingTypeEnum = {})); /**
* @export
* @enum {string}
*/
var VariableVariableCategoryNameEnum;
(function (VariableVariableCategoryNameEnum) {
    VariableVariableCategoryNameEnum["Activity"] = "Activity";
    VariableVariableCategoryNameEnum["Books"] = "Books";
    VariableVariableCategoryNameEnum["CausesOfIllness"] = "Causes of Illness";
    VariableVariableCategoryNameEnum["CognitivePerformance"] = "Cognitive Performance";
    VariableVariableCategoryNameEnum["Conditions"] = "Conditions";
    VariableVariableCategoryNameEnum["Emotions"] = "Emotions";
    VariableVariableCategoryNameEnum["Environment"] = "Environment";
    VariableVariableCategoryNameEnum["Foods"] = "Foods";
    VariableVariableCategoryNameEnum["Goals"] = "Goals";
    VariableVariableCategoryNameEnum["Locations"] = "Locations";
    VariableVariableCategoryNameEnum["Miscellaneous"] = "Miscellaneous";
    VariableVariableCategoryNameEnum["MoviesAndTv"] = "Movies and TV";
    VariableVariableCategoryNameEnum["Music"] = "Music";
    VariableVariableCategoryNameEnum["Nutrients"] = "Nutrients";
    VariableVariableCategoryNameEnum["Payments"] = "Payments";
    VariableVariableCategoryNameEnum["PhysicalActivities"] = "Physical Activities";
    VariableVariableCategoryNameEnum["Physique"] = "Physique";
    VariableVariableCategoryNameEnum["Sleep"] = "Sleep";
    VariableVariableCategoryNameEnum["SocialInteractions"] = "Social Interactions";
    VariableVariableCategoryNameEnum["Software"] = "Software";
    VariableVariableCategoryNameEnum["Symptoms"] = "Symptoms";
    VariableVariableCategoryNameEnum["Treatments"] = "Treatments";
    VariableVariableCategoryNameEnum["VitalSigns"] = "Vital Signs";
})(VariableVariableCategoryNameEnum = exports.VariableVariableCategoryNameEnum || (exports.VariableVariableCategoryNameEnum = {}));
function VariableFromJSON(json) {
    return VariableFromJSONTyped(json, false);
}
exports.VariableFromJSON = VariableFromJSON;
function VariableFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'actionArray': !(0, runtime_1.exists)(json, 'actionArray') ? undefined : (json['actionArray'].map(_1.TrackingReminderNotificationActionFromJSON)),
        'alias': !(0, runtime_1.exists)(json, 'alias') ? undefined : json['alias'],
        'availableUnits': !(0, runtime_1.exists)(json, 'availableUnits') ? undefined : (json['availableUnits'].map(_1.UnitFromJSON)),
        'bestStudyLink': !(0, runtime_1.exists)(json, 'bestStudyLink') ? undefined : json['bestStudyLink'],
        'bestStudyCard': !(0, runtime_1.exists)(json, 'bestStudyCard') ? undefined : (0, _1.CardFromJSON)(json['bestStudyCard']),
        'bestUserStudyLink': !(0, runtime_1.exists)(json, 'bestUserStudyLink') ? undefined : json['bestUserStudyLink'],
        'bestUserStudyCard': !(0, runtime_1.exists)(json, 'bestUserStudyCard') ? undefined : (0, _1.CardFromJSON)(json['bestUserStudyCard']),
        'bestPopulationStudyLink': !(0, runtime_1.exists)(json, 'bestPopulationStudyLink') ? undefined : json['bestPopulationStudyLink'],
        'bestPopulationStudyCard': !(0, runtime_1.exists)(json, 'bestPopulationStudyCard') ? undefined : (0, _1.CardFromJSON)(json['bestPopulationStudyCard']),
        'optimalValueMessage': !(0, runtime_1.exists)(json, 'optimalValueMessage') ? undefined : json['optimalValueMessage'],
        'commonOptimalValueMessage': !(0, runtime_1.exists)(json, 'commonOptimalValueMessage') ? undefined : json['commonOptimalValueMessage'],
        'userOptimalValueMessage': !(0, runtime_1.exists)(json, 'userOptimalValueMessage') ? undefined : json['userOptimalValueMessage'],
        'card': !(0, runtime_1.exists)(json, 'card') ? undefined : (0, _1.CardFromJSON)(json['card']),
        'causeOnly': !(0, runtime_1.exists)(json, 'causeOnly') ? undefined : json['causeOnly'],
        'charts': !(0, runtime_1.exists)(json, 'charts') ? undefined : (0, _1.VariableChartsFromJSON)(json['charts']),
        'chartsLinkDynamic': !(0, runtime_1.exists)(json, 'chartsLinkDynamic') ? undefined : json['chartsLinkDynamic'],
        'chartsLinkEmail': !(0, runtime_1.exists)(json, 'chartsLinkEmail') ? undefined : json['chartsLinkEmail'],
        'chartsLinkFacebook': !(0, runtime_1.exists)(json, 'chartsLinkFacebook') ? undefined : json['chartsLinkFacebook'],
        'chartsLinkGoogle': !(0, runtime_1.exists)(json, 'chartsLinkGoogle') ? undefined : json['chartsLinkGoogle'],
        'chartsLinkStatic': !(0, runtime_1.exists)(json, 'chartsLinkStatic') ? undefined : json['chartsLinkStatic'],
        'chartsLinkTwitter': !(0, runtime_1.exists)(json, 'chartsLinkTwitter') ? undefined : json['chartsLinkTwitter'],
        'childCommonTagVariables': !(0, runtime_1.exists)(json, 'childCommonTagVariables') ? undefined : (json['childCommonTagVariables'].map(VariableFromJSON)),
        'childUserTagVariables': !(0, runtime_1.exists)(json, 'childUserTagVariables') ? undefined : (json['childUserTagVariables'].map(VariableFromJSON)),
        'clientId': !(0, runtime_1.exists)(json, 'clientId') ? undefined : json['clientId'],
        'combinationOperation': !(0, runtime_1.exists)(json, 'combinationOperation') ? undefined : json['combinationOperation'],
        'commonAlias': !(0, runtime_1.exists)(json, 'commonAlias') ? undefined : json['commonAlias'],
        'commonTaggedVariables': !(0, runtime_1.exists)(json, 'commonTaggedVariables') ? undefined : (json['commonTaggedVariables'].map(VariableFromJSON)),
        'commonTagVariables': !(0, runtime_1.exists)(json, 'commonTagVariables') ? undefined : (json['commonTagVariables'].map(VariableFromJSON)),
        'createdAt': !(0, runtime_1.exists)(json, 'createdAt') ? undefined : json['createdAt'],
        'dataSourceNames': !(0, runtime_1.exists)(json, 'dataSourceNames') ? undefined : json['dataSourceNames'],
        'dataSources': !(0, runtime_1.exists)(json, 'dataSources') ? undefined : (json['dataSources'].map(_1.DataSourceFromJSON)),
        'description': !(0, runtime_1.exists)(json, 'description') ? undefined : json['description'],
        'displayName': !(0, runtime_1.exists)(json, 'displayName') ? undefined : json['displayName'],
        'durationOfAction': !(0, runtime_1.exists)(json, 'durationOfAction') ? undefined : json['durationOfAction'],
        'durationOfActionInHours': !(0, runtime_1.exists)(json, 'durationOfActionInHours') ? undefined : json['durationOfActionInHours'],
        'earliestFillingTime': !(0, runtime_1.exists)(json, 'earliestFillingTime') ? undefined : json['earliestFillingTime'],
        'earliestMeasurementTime': !(0, runtime_1.exists)(json, 'earliestMeasurementTime') ? undefined : json['earliestMeasurementTime'],
        'earliestSourceTime': !(0, runtime_1.exists)(json, 'earliestSourceTime') ? undefined : json['earliestSourceTime'],
        'errorMessage': !(0, runtime_1.exists)(json, 'errorMessage') ? undefined : json['errorMessage'],
        'experimentEndTime': !(0, runtime_1.exists)(json, 'experimentEndTime') ? undefined : json['experimentEndTime'],
        'experimentStartTime': !(0, runtime_1.exists)(json, 'experimentStartTime') ? undefined : json['experimentStartTime'],
        'fillingType': !(0, runtime_1.exists)(json, 'fillingType') ? undefined : json['fillingType'],
        'fillingValue': !(0, runtime_1.exists)(json, 'fillingValue') ? undefined : json['fillingValue'],
        'iconIcon': !(0, runtime_1.exists)(json, 'iconIcon') ? undefined : json['iconIcon'],
        'id': json['id'],
        'imageUrl': !(0, runtime_1.exists)(json, 'imageUrl') ? undefined : json['imageUrl'],
        'informationalUrl': !(0, runtime_1.exists)(json, 'informationalUrl') ? undefined : json['informationalUrl'],
        'ingredientOfCommonTagVariables': !(0, runtime_1.exists)(json, 'ingredientOfCommonTagVariables') ? undefined : (json['ingredientOfCommonTagVariables'].map(VariableFromJSON)),
        'ingredientCommonTagVariables': !(0, runtime_1.exists)(json, 'ingredientCommonTagVariables') ? undefined : (json['ingredientCommonTagVariables'].map(VariableFromJSON)),
        'ingredientOfUserTagVariables': !(0, runtime_1.exists)(json, 'ingredientOfUserTagVariables') ? undefined : (json['ingredientOfUserTagVariables'].map(VariableFromJSON)),
        'ingredientUserTagVariables': !(0, runtime_1.exists)(json, 'ingredientUserTagVariables') ? undefined : (json['ingredientUserTagVariables'].map(VariableFromJSON)),
        'inputType': !(0, runtime_1.exists)(json, 'inputType') ? undefined : json['inputType'],
        'ionIcon': !(0, runtime_1.exists)(json, 'ionIcon') ? undefined : json['ionIcon'],
        'joinedCommonTagVariables': !(0, runtime_1.exists)(json, 'joinedCommonTagVariables') ? undefined : (json['joinedCommonTagVariables'].map(VariableFromJSON)),
        'joinedUserTagVariables': !(0, runtime_1.exists)(json, 'joinedUserTagVariables') ? undefined : (json['joinedUserTagVariables'].map(VariableFromJSON)),
        'joinWith': !(0, runtime_1.exists)(json, 'joinWith') ? undefined : json['joinWith'],
        'kurtosis': !(0, runtime_1.exists)(json, 'kurtosis') ? undefined : json['kurtosis'],
        'lastProcessedDailyValue': !(0, runtime_1.exists)(json, 'lastProcessedDailyValue') ? undefined : json['lastProcessedDailyValue'],
        'lastSuccessfulUpdateTime': !(0, runtime_1.exists)(json, 'lastSuccessfulUpdateTime') ? undefined : json['lastSuccessfulUpdateTime'],
        'lastValue': !(0, runtime_1.exists)(json, 'lastValue') ? undefined : json['lastValue'],
        'latestFillingTime': !(0, runtime_1.exists)(json, 'latestFillingTime') ? undefined : json['latestFillingTime'],
        'latestMeasurementTime': !(0, runtime_1.exists)(json, 'latestMeasurementTime') ? undefined : json['latestMeasurementTime'],
        'latestSourceTime': !(0, runtime_1.exists)(json, 'latestSourceTime') ? undefined : json['latestSourceTime'],
        'latestUserMeasurementTime': !(0, runtime_1.exists)(json, 'latestUserMeasurementTime') ? undefined : json['latestUserMeasurementTime'],
        'latitude': !(0, runtime_1.exists)(json, 'latitude') ? undefined : json['latitude'],
        'location': !(0, runtime_1.exists)(json, 'location') ? undefined : json['location'],
        'longitude': !(0, runtime_1.exists)(json, 'longitude') ? undefined : json['longitude'],
        'manualTracking': !(0, runtime_1.exists)(json, 'manualTracking') ? undefined : json['manualTracking'],
        'maximumAllowedDailyValue': !(0, runtime_1.exists)(json, 'maximumAllowedDailyValue') ? undefined : json['maximumAllowedDailyValue'],
        'maximumAllowedValue': !(0, runtime_1.exists)(json, 'maximumAllowedValue') ? undefined : json['maximumAllowedValue'],
        'maximumRecordedDailyValue': !(0, runtime_1.exists)(json, 'maximumRecordedDailyValue') ? undefined : json['maximumRecordedDailyValue'],
        'maximumRecordedValue': !(0, runtime_1.exists)(json, 'maximumRecordedValue') ? undefined : json['maximumRecordedValue'],
        'mean': !(0, runtime_1.exists)(json, 'mean') ? undefined : json['mean'],
        'measurementsAtLastAnalysis': !(0, runtime_1.exists)(json, 'measurementsAtLastAnalysis') ? undefined : json['measurementsAtLastAnalysis'],
        'median': !(0, runtime_1.exists)(json, 'median') ? undefined : json['median'],
        'minimumAllowedValue': !(0, runtime_1.exists)(json, 'minimumAllowedValue') ? undefined : json['minimumAllowedValue'],
        'minimumAllowedDailyValue': !(0, runtime_1.exists)(json, 'minimumAllowedDailyValue') ? undefined : json['minimumAllowedDailyValue'],
        'minimumNonZeroValue': !(0, runtime_1.exists)(json, 'minimumNonZeroValue') ? undefined : json['minimumNonZeroValue'],
        'minimumRecordedValue': !(0, runtime_1.exists)(json, 'minimumRecordedValue') ? undefined : json['minimumRecordedValue'],
        'mostCommonConnectorId': !(0, runtime_1.exists)(json, 'mostCommonConnectorId') ? undefined : json['mostCommonConnectorId'],
        'mostCommonOriginalUnitId': !(0, runtime_1.exists)(json, 'mostCommonOriginalUnitId') ? undefined : json['mostCommonOriginalUnitId'],
        'mostCommonUnitId': !(0, runtime_1.exists)(json, 'mostCommonUnitId') ? undefined : json['mostCommonUnitId'],
        'mostCommonValue': !(0, runtime_1.exists)(json, 'mostCommonValue') ? undefined : json['mostCommonValue'],
        'name': json['name'],
        'numberOfAggregateCorrelationsAsCause': !(0, runtime_1.exists)(json, 'numberOfAggregateCorrelationsAsCause') ? undefined : json['numberOfAggregateCorrelationsAsCause'],
        'numberOfAggregateCorrelationsAsEffect': !(0, runtime_1.exists)(json, 'numberOfAggregateCorrelationsAsEffect') ? undefined : json['numberOfAggregateCorrelationsAsEffect'],
        'numberOfChanges': !(0, runtime_1.exists)(json, 'numberOfChanges') ? undefined : json['numberOfChanges'],
        'numberOfCorrelations': !(0, runtime_1.exists)(json, 'numberOfCorrelations') ? undefined : json['numberOfCorrelations'],
        'numberOfCorrelationsAsCause': !(0, runtime_1.exists)(json, 'numberOfCorrelationsAsCause') ? undefined : json['numberOfCorrelationsAsCause'],
        'numberOfCorrelationsAsEffect': !(0, runtime_1.exists)(json, 'numberOfCorrelationsAsEffect') ? undefined : json['numberOfCorrelationsAsEffect'],
        'numberOfProcessedDailyMeasurements': !(0, runtime_1.exists)(json, 'numberOfProcessedDailyMeasurements') ? undefined : json['numberOfProcessedDailyMeasurements'],
        'numberOfRawMeasurements': !(0, runtime_1.exists)(json, 'numberOfRawMeasurements') ? undefined : json['numberOfRawMeasurements'],
        'numberOfTrackingReminders': !(0, runtime_1.exists)(json, 'numberOfTrackingReminders') ? undefined : json['numberOfTrackingReminders'],
        'numberOfUniqueDailyValues': !(0, runtime_1.exists)(json, 'numberOfUniqueDailyValues') ? undefined : json['numberOfUniqueDailyValues'],
        'numberOfUniqueValues': !(0, runtime_1.exists)(json, 'numberOfUniqueValues') ? undefined : json['numberOfUniqueValues'],
        'numberOfUserCorrelationsAsCause': !(0, runtime_1.exists)(json, 'numberOfUserCorrelationsAsCause') ? undefined : json['numberOfUserCorrelationsAsCause'],
        'numberOfUserCorrelationsAsEffect': !(0, runtime_1.exists)(json, 'numberOfUserCorrelationsAsEffect') ? undefined : json['numberOfUserCorrelationsAsEffect'],
        'numberOfUserVariables': !(0, runtime_1.exists)(json, 'numberOfUserVariables') ? undefined : json['numberOfUserVariables'],
        'onsetDelay': !(0, runtime_1.exists)(json, 'onsetDelay') ? undefined : json['onsetDelay'],
        'onsetDelayInHours': !(0, runtime_1.exists)(json, 'onsetDelayInHours') ? undefined : json['onsetDelayInHours'],
        'outcome': !(0, runtime_1.exists)(json, 'outcome') ? undefined : json['outcome'],
        'outcomeOfInterest': !(0, runtime_1.exists)(json, 'outcomeOfInterest') ? undefined : json['outcomeOfInterest'],
        'parentCommonTagVariables': !(0, runtime_1.exists)(json, 'parentCommonTagVariables') ? undefined : (json['parentCommonTagVariables'].map(VariableFromJSON)),
        'parentUserTagVariables': !(0, runtime_1.exists)(json, 'parentUserTagVariables') ? undefined : (json['parentUserTagVariables'].map(VariableFromJSON)),
        'pngPath': !(0, runtime_1.exists)(json, 'pngPath') ? undefined : json['pngPath'],
        'pngUrl': !(0, runtime_1.exists)(json, 'pngUrl') ? undefined : json['pngUrl'],
        'predictorOfInterest': !(0, runtime_1.exists)(json, 'predictorOfInterest') ? undefined : json['predictorOfInterest'],
        'price': !(0, runtime_1.exists)(json, 'price') ? undefined : json['price'],
        'productUrl': !(0, runtime_1.exists)(json, 'productUrl') ? undefined : json['productUrl'],
        '_public': !(0, runtime_1.exists)(json, 'public') ? undefined : json['public'],
        'question': !(0, runtime_1.exists)(json, 'question') ? undefined : json['question'],
        'longQuestion': !(0, runtime_1.exists)(json, 'longQuestion') ? undefined : json['longQuestion'],
        'rawMeasurementsAtLastAnalysis': !(0, runtime_1.exists)(json, 'rawMeasurementsAtLastAnalysis') ? undefined : json['rawMeasurementsAtLastAnalysis'],
        'secondMostCommonValue': !(0, runtime_1.exists)(json, 'secondMostCommonValue') ? undefined : json['secondMostCommonValue'],
        'secondToLastValue': !(0, runtime_1.exists)(json, 'secondToLastValue') ? undefined : json['secondToLastValue'],
        'shareUserMeasurements': !(0, runtime_1.exists)(json, 'shareUserMeasurements') ? undefined : json['shareUserMeasurements'],
        'skewness': !(0, runtime_1.exists)(json, 'skewness') ? undefined : json['skewness'],
        'standardDeviation': !(0, runtime_1.exists)(json, 'standardDeviation') ? undefined : json['standardDeviation'],
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
        'subtitle': !(0, runtime_1.exists)(json, 'subtitle') ? undefined : json['subtitle'],
        'svgUrl': !(0, runtime_1.exists)(json, 'svgUrl') ? undefined : json['svgUrl'],
        'thirdMostCommonValue': !(0, runtime_1.exists)(json, 'thirdMostCommonValue') ? undefined : json['thirdMostCommonValue'],
        'thirdToLastValue': !(0, runtime_1.exists)(json, 'thirdToLastValue') ? undefined : json['thirdToLastValue'],
        'trackingInstructions': !(0, runtime_1.exists)(json, 'trackingInstructions') ? undefined : json['trackingInstructions'],
        'trackingInstructionsCard': !(0, runtime_1.exists)(json, 'trackingInstructionsCard') ? undefined : (0, _1.CardFromJSON)(json['trackingInstructionsCard']),
        'unit': !(0, runtime_1.exists)(json, 'unit') ? undefined : (0, _1.UnitFromJSON)(json['unit']),
        'unitAbbreviatedName': !(0, runtime_1.exists)(json, 'unitAbbreviatedName') ? undefined : json['unitAbbreviatedName'],
        'unitCategoryId': !(0, runtime_1.exists)(json, 'unitCategoryId') ? undefined : json['unitCategoryId'],
        'unitCategoryName': !(0, runtime_1.exists)(json, 'unitCategoryName') ? undefined : json['unitCategoryName'],
        'unitId': !(0, runtime_1.exists)(json, 'unitId') ? undefined : json['unitId'],
        'unitName': !(0, runtime_1.exists)(json, 'unitName') ? undefined : json['unitName'],
        'upc': !(0, runtime_1.exists)(json, 'upc') ? undefined : json['upc'],
        'updated': !(0, runtime_1.exists)(json, 'updated') ? undefined : json['updated'],
        'updatedAt': !(0, runtime_1.exists)(json, 'updatedAt') ? undefined : json['updatedAt'],
        'updatedTime': !(0, runtime_1.exists)(json, 'updatedTime') ? undefined : json['updatedTime'],
        'userId': json['userId'],
        'userTaggedVariables': !(0, runtime_1.exists)(json, 'userTaggedVariables') ? undefined : (json['userTaggedVariables'].map(VariableFromJSON)),
        'userTagVariables': !(0, runtime_1.exists)(json, 'userTagVariables') ? undefined : (json['userTagVariables'].map(VariableFromJSON)),
        'userVariableUnitAbbreviatedName': !(0, runtime_1.exists)(json, 'userVariableUnitAbbreviatedName') ? undefined : json['userVariableUnitAbbreviatedName'],
        'userVariableUnitCategoryId': !(0, runtime_1.exists)(json, 'userVariableUnitCategoryId') ? undefined : json['userVariableUnitCategoryId'],
        'userVariableUnitCategoryName': !(0, runtime_1.exists)(json, 'userVariableUnitCategoryName') ? undefined : json['userVariableUnitCategoryName'],
        'userVariableUnitId': !(0, runtime_1.exists)(json, 'userVariableUnitId') ? undefined : json['userVariableUnitId'],
        'userVariableUnitName': !(0, runtime_1.exists)(json, 'userVariableUnitName') ? undefined : json['userVariableUnitName'],
        'variableCategory': !(0, runtime_1.exists)(json, 'variableCategory') ? undefined : (0, _1.VariableCategoryFromJSON)(json['variableCategory']),
        'joinedVariables': !(0, runtime_1.exists)(json, 'joinedVariables') ? undefined : (json['joinedVariables'].map(VariableFromJSON)),
        'valence': !(0, runtime_1.exists)(json, 'valence') ? undefined : json['valence'],
        'variableCategoryId': !(0, runtime_1.exists)(json, 'variableCategoryId') ? undefined : json['variableCategoryId'],
        'variableCategoryName': !(0, runtime_1.exists)(json, 'variableCategoryName') ? undefined : json['variableCategoryName'],
        'variableId': json['variableId'],
        'variableName': !(0, runtime_1.exists)(json, 'variableName') ? undefined : json['variableName'],
        'variance': !(0, runtime_1.exists)(json, 'variance') ? undefined : json['variance'],
        'wikipediaTitle': !(0, runtime_1.exists)(json, 'wikipediaTitle') ? undefined : json['wikipediaTitle'],
    };
}
exports.VariableFromJSONTyped = VariableFromJSONTyped;
function VariableToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'actionArray': value.actionArray === undefined ? undefined : (value.actionArray.map(_1.TrackingReminderNotificationActionToJSON)),
        'alias': value.alias,
        'availableUnits': value.availableUnits === undefined ? undefined : (value.availableUnits.map(_1.UnitToJSON)),
        'bestStudyLink': value.bestStudyLink,
        'bestStudyCard': (0, _1.CardToJSON)(value.bestStudyCard),
        'bestUserStudyLink': value.bestUserStudyLink,
        'bestUserStudyCard': (0, _1.CardToJSON)(value.bestUserStudyCard),
        'bestPopulationStudyLink': value.bestPopulationStudyLink,
        'bestPopulationStudyCard': (0, _1.CardToJSON)(value.bestPopulationStudyCard),
        'optimalValueMessage': value.optimalValueMessage,
        'commonOptimalValueMessage': value.commonOptimalValueMessage,
        'userOptimalValueMessage': value.userOptimalValueMessage,
        'card': (0, _1.CardToJSON)(value.card),
        'causeOnly': value.causeOnly,
        'charts': (0, _1.VariableChartsToJSON)(value.charts),
        'chartsLinkDynamic': value.chartsLinkDynamic,
        'chartsLinkEmail': value.chartsLinkEmail,
        'chartsLinkFacebook': value.chartsLinkFacebook,
        'chartsLinkGoogle': value.chartsLinkGoogle,
        'chartsLinkStatic': value.chartsLinkStatic,
        'chartsLinkTwitter': value.chartsLinkTwitter,
        'childCommonTagVariables': value.childCommonTagVariables === undefined ? undefined : (value.childCommonTagVariables.map(VariableToJSON)),
        'childUserTagVariables': value.childUserTagVariables === undefined ? undefined : (value.childUserTagVariables.map(VariableToJSON)),
        'clientId': value.clientId,
        'combinationOperation': value.combinationOperation,
        'commonAlias': value.commonAlias,
        'commonTaggedVariables': value.commonTaggedVariables === undefined ? undefined : (value.commonTaggedVariables.map(VariableToJSON)),
        'commonTagVariables': value.commonTagVariables === undefined ? undefined : (value.commonTagVariables.map(VariableToJSON)),
        'createdAt': value.createdAt,
        'dataSourceNames': value.dataSourceNames,
        'dataSources': value.dataSources === undefined ? undefined : (value.dataSources.map(_1.DataSourceToJSON)),
        'description': value.description,
        'displayName': value.displayName,
        'durationOfAction': value.durationOfAction,
        'durationOfActionInHours': value.durationOfActionInHours,
        'earliestFillingTime': value.earliestFillingTime,
        'earliestMeasurementTime': value.earliestMeasurementTime,
        'earliestSourceTime': value.earliestSourceTime,
        'errorMessage': value.errorMessage,
        'experimentEndTime': value.experimentEndTime,
        'experimentStartTime': value.experimentStartTime,
        'fillingType': value.fillingType,
        'fillingValue': value.fillingValue,
        'iconIcon': value.iconIcon,
        'id': value.id,
        'imageUrl': value.imageUrl,
        'informationalUrl': value.informationalUrl,
        'ingredientOfCommonTagVariables': value.ingredientOfCommonTagVariables === undefined ? undefined : (value.ingredientOfCommonTagVariables.map(VariableToJSON)),
        'ingredientCommonTagVariables': value.ingredientCommonTagVariables === undefined ? undefined : (value.ingredientCommonTagVariables.map(VariableToJSON)),
        'ingredientOfUserTagVariables': value.ingredientOfUserTagVariables === undefined ? undefined : (value.ingredientOfUserTagVariables.map(VariableToJSON)),
        'ingredientUserTagVariables': value.ingredientUserTagVariables === undefined ? undefined : (value.ingredientUserTagVariables.map(VariableToJSON)),
        'inputType': value.inputType,
        'ionIcon': value.ionIcon,
        'joinedCommonTagVariables': value.joinedCommonTagVariables === undefined ? undefined : (value.joinedCommonTagVariables.map(VariableToJSON)),
        'joinedUserTagVariables': value.joinedUserTagVariables === undefined ? undefined : (value.joinedUserTagVariables.map(VariableToJSON)),
        'joinWith': value.joinWith,
        'kurtosis': value.kurtosis,
        'lastProcessedDailyValue': value.lastProcessedDailyValue,
        'lastSuccessfulUpdateTime': value.lastSuccessfulUpdateTime,
        'lastValue': value.lastValue,
        'latestFillingTime': value.latestFillingTime,
        'latestMeasurementTime': value.latestMeasurementTime,
        'latestSourceTime': value.latestSourceTime,
        'latestUserMeasurementTime': value.latestUserMeasurementTime,
        'latitude': value.latitude,
        'location': value.location,
        'longitude': value.longitude,
        'manualTracking': value.manualTracking,
        'maximumAllowedDailyValue': value.maximumAllowedDailyValue,
        'maximumAllowedValue': value.maximumAllowedValue,
        'maximumRecordedDailyValue': value.maximumRecordedDailyValue,
        'maximumRecordedValue': value.maximumRecordedValue,
        'mean': value.mean,
        'measurementsAtLastAnalysis': value.measurementsAtLastAnalysis,
        'median': value.median,
        'minimumAllowedValue': value.minimumAllowedValue,
        'minimumAllowedDailyValue': value.minimumAllowedDailyValue,
        'minimumNonZeroValue': value.minimumNonZeroValue,
        'minimumRecordedValue': value.minimumRecordedValue,
        'mostCommonConnectorId': value.mostCommonConnectorId,
        'mostCommonOriginalUnitId': value.mostCommonOriginalUnitId,
        'mostCommonUnitId': value.mostCommonUnitId,
        'mostCommonValue': value.mostCommonValue,
        'name': value.name,
        'numberOfAggregateCorrelationsAsCause': value.numberOfAggregateCorrelationsAsCause,
        'numberOfAggregateCorrelationsAsEffect': value.numberOfAggregateCorrelationsAsEffect,
        'numberOfChanges': value.numberOfChanges,
        'numberOfCorrelations': value.numberOfCorrelations,
        'numberOfCorrelationsAsCause': value.numberOfCorrelationsAsCause,
        'numberOfCorrelationsAsEffect': value.numberOfCorrelationsAsEffect,
        'numberOfProcessedDailyMeasurements': value.numberOfProcessedDailyMeasurements,
        'numberOfRawMeasurements': value.numberOfRawMeasurements,
        'numberOfTrackingReminders': value.numberOfTrackingReminders,
        'numberOfUniqueDailyValues': value.numberOfUniqueDailyValues,
        'numberOfUniqueValues': value.numberOfUniqueValues,
        'numberOfUserCorrelationsAsCause': value.numberOfUserCorrelationsAsCause,
        'numberOfUserCorrelationsAsEffect': value.numberOfUserCorrelationsAsEffect,
        'numberOfUserVariables': value.numberOfUserVariables,
        'onsetDelay': value.onsetDelay,
        'onsetDelayInHours': value.onsetDelayInHours,
        'outcome': value.outcome,
        'outcomeOfInterest': value.outcomeOfInterest,
        'parentCommonTagVariables': value.parentCommonTagVariables === undefined ? undefined : (value.parentCommonTagVariables.map(VariableToJSON)),
        'parentUserTagVariables': value.parentUserTagVariables === undefined ? undefined : (value.parentUserTagVariables.map(VariableToJSON)),
        'pngPath': value.pngPath,
        'pngUrl': value.pngUrl,
        'predictorOfInterest': value.predictorOfInterest,
        'price': value.price,
        'productUrl': value.productUrl,
        'public': value._public,
        'question': value.question,
        'longQuestion': value.longQuestion,
        'rawMeasurementsAtLastAnalysis': value.rawMeasurementsAtLastAnalysis,
        'secondMostCommonValue': value.secondMostCommonValue,
        'secondToLastValue': value.secondToLastValue,
        'shareUserMeasurements': value.shareUserMeasurements,
        'skewness': value.skewness,
        'standardDeviation': value.standardDeviation,
        'status': value.status,
        'subtitle': value.subtitle,
        'svgUrl': value.svgUrl,
        'thirdMostCommonValue': value.thirdMostCommonValue,
        'thirdToLastValue': value.thirdToLastValue,
        'trackingInstructions': value.trackingInstructions,
        'trackingInstructionsCard': (0, _1.CardToJSON)(value.trackingInstructionsCard),
        'unit': (0, _1.UnitToJSON)(value.unit),
        'unitAbbreviatedName': value.unitAbbreviatedName,
        'unitCategoryId': value.unitCategoryId,
        'unitCategoryName': value.unitCategoryName,
        'unitId': value.unitId,
        'unitName': value.unitName,
        'upc': value.upc,
        'updated': value.updated,
        'updatedAt': value.updatedAt,
        'updatedTime': value.updatedTime,
        'userId': value.userId,
        'userTaggedVariables': value.userTaggedVariables === undefined ? undefined : (value.userTaggedVariables.map(VariableToJSON)),
        'userTagVariables': value.userTagVariables === undefined ? undefined : (value.userTagVariables.map(VariableToJSON)),
        'userVariableUnitAbbreviatedName': value.userVariableUnitAbbreviatedName,
        'userVariableUnitCategoryId': value.userVariableUnitCategoryId,
        'userVariableUnitCategoryName': value.userVariableUnitCategoryName,
        'userVariableUnitId': value.userVariableUnitId,
        'userVariableUnitName': value.userVariableUnitName,
        'variableCategory': (0, _1.VariableCategoryToJSON)(value.variableCategory),
        'joinedVariables': value.joinedVariables === undefined ? undefined : (value.joinedVariables.map(VariableToJSON)),
        'valence': value.valence,
        'variableCategoryId': value.variableCategoryId,
        'variableCategoryName': value.variableCategoryName,
        'variableId': value.variableId,
        'variableName': value.variableName,
        'variance': value.variance,
        'wikipediaTitle': value.wikipediaTitle,
    };
}
exports.VariableToJSON = VariableToJSON;
//# sourceMappingURL=Variable.js.map
