name: PR update

on:
  push:
    branches: develop

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: update all prs
        uses: mikepsinn/pr-updater-action@master
        with:
          token: ${{ secrets.USER_TOKEN }}