# For info on getting the latest rdme version and obtaining your API_DEFINITION_ID,
# see our docs: https://docs.readme.com/docs/rdme#example-syncing-an-openapi-definition
name: Sync OAS to ReadMe
on:
  push:
    branches:
      - open-api-v3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/rdme@7.0.1
        with:
          rdme: openapi specification/cure-dao-open-api-v3.yml --key=${{ secrets.READMEIO_KEY }} --id=${{ secrets.API_DEFINITION_ID }}
